### ISSUE TITLE
Convert non-Manhattan compliant models' model_mod.html and README files to reStructuredText

### ISSUE THREAD

**Issue by johnsonb-ucar** [NCAR/DART#100]
_Note: I reference pull request number 61 in this issue, but am not using the `hashtag 61` Github syntax that we typically use to link issues to pull requests because this issue should not be closed when pull request number 61 is merged._

### Issue Overview

An existing pull request, number 61, converted all of the Manhattan-compliant models' model_mod.html and README files to reStructuredText.

There are 15 subdirectories remaining in the `$DARTROOT/models` directory that have yet to be converted:

1. `MITgcm_annulus`
2. `MITgcm_ocean`
3. `NAAPS`
4. `NCOMMAS`
5. `cam-old`
6. `clm`
7. `coamps`
8. `dynamo`
9. `forced_barotropic`
10. `ikeda`
11. `mpas_ocn`
12. `pe2lyr`
13. `sqg`
14. `tiegcm`
15. `utilities`

I plan to convert these directories gradually, perhaps doing a few models per week.

### One discussion question

Should I convert `$DARTROOT/models/utilities/default_model_mod.html` beforehand (perhaps including it in pull request number 61) so that we have an empty README.rst template that developers can make use of?

**Comment by hkershaw-brown** [comment]
Seems like an excellent idea to have a template to work from. 
How about a template model_mod.rst in the DART/models/template directory? 

The default_model_mod ( I think ) is for model_mods to use when they don't need to write a model specific routines. 

Also, **hot take**: I think 'not Manhattan compliant' means 'does not compile' so why not remove these model mod directories from the master? (note I don't mean do this for pull request 61)

**Comment by nancycollins** [comment]
i think the ideas for leaving the directories were 1) when users cd into the models directory, they'd see an impressive and broad list of models used with dart; and 2) if they saw a model there that wasn't yet manhattan compliant but they wanted to use, they could contact us and it would be less work to convert a lanai version compared to starting from scratch.

all the non-compliant directories should have some kind of documentation saying the latter bit - if you're interested in using this model with manhattan, contact dart for support in converting it, etc.   i am not sure they do.

**Comment by hkershaw-brown** [comment]
out of date, html has been converted to rst.
