### ISSUE TITLE
gmi converter gfortran not compiling

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#109]
The `observations/obs_converters/GMI/gmi_L1_mod.f90` file is failing to compile with gfortran 9.2.0 and 'the latest'  HDF-EOS5 libraries (built from `hdf5-1.8.19.tar.gz` - which might not be the latest version -- see cheyenne's h5dump version info) https://wiki.earthdata.nasa.gov/display/DAS/Toolkit+Downloads

There is a series of 
```
../../../../observations/obs_converters/GMI/gmi_L1_mod.f90:658:55:

  658 | call h5dread_f(dset_id, mem_type, array, dims, hdferr); call h5check(hdferr, 'h5dread_f')
      |                                                       1
Error: There is no specific subroutine for the generic 'h5dread_f' at (1)
```

messages.  The same code builds and runs on cheyenne with the following environment:
```
0[2029] cheyenne5:/<8>19.0.5/bin > h5dump --version
h5dump: Version 1.10.7
0[2030] cheyenne5:/<8>19.0.5/bin > module list

Currently Loaded Modules:
  1) ncarenv/1.3    3) ncarcompilers/0.5.0   5) netcdf/4.7.4   7) nco/4.9.5      9) diffuse/0.4.8
  2) intel/19.0.5   4) mpt/2.22              6) mkl/2019.0.5   8) ncview/2.1.7  10) hdf-eos5/5.1.16

```

The HDF5 libraries I built with gfortran are indeed 'older' :
```
0[1023] cisl-minnetonka:~/gnu/gnu_9.2.0/bin % ./h5dump --version
h5dump: Version 1.8.19
```

**Comment by hkershaw-brown** [comment]
Hi Tim,  I'm going to try and reproduce this compile error on my mac. 
Following the instructions at https://wiki.earthdata.nasa.gov/display/DAS/Toolkit+Downloads

````
HDF-EOS5
Latest Release
Release v5.1.16
HDF-EOS5.1.16.tar.Z
HDF-EOS5.1.16_TESTDRIVERS.tar.Z
HDF-EOS5_REF.pdf
HDF-EOS5_UG.pdf
hdf5-1.8.19.tar.gz
szip-2.1.1.tar.gz
````

HDF5 1.8.19 is what nasa suggests.

**Comment by timhoar** [comment]
The `observations/obs_converters/AIRS/BUILD_HDF-EOS.sh` script is a helpful way to build support for both HDF-EOS and HDF-EOS5.  It is what I used to build the libraries on my Mac (which is the hdf5-1.8.19 version, btw). The version on Cheyenne is newer than that.

This morning I tried to install the hdf-1.10.7  (to match the version on Cheyenne) to no avail:
```
...
Integer attribute value:                     9999
Status returned by HE5_PTdetach() :          0 
Status returned by HE5_PTclose() :           0 
./he5_pt_readattrs
make[2]: *** [pt_write_test] Segmentation fault: 11
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1
```

**Comment by hkershaw-brown** [comment]
I have 1.10.7 on my mac from macports. 

I tried building 1.8.19 on my mac, which builds but make check gives:

````
Status returned by HE5_PTwritelevel() :   0 
Status returned by HE5_PTdetach() :       0 
make[2]: *** [pt_write_test] Illegal instruction: 4
make[1]: *** [check-am] Error 2
````

Looking at the differences between 1.8.19 and 1.10.7 there is a configure option `--enable-fortran2003` for 1.8.19.   Tried this, but still got the `Error: There is no specific subroutine for the generic 'h5dread_f`

**Comment by hkershaw-brown** [comment]
I build hdf5 1.10.7 with gcc.  The macports 1.10.7 is clang. 

With gcc 1.10.7 the GMI convert does build against HDF-EOS5 (If you believe me)
![Screen Shot 2020-12-31 at 11 02 53 AM](https://user-images.githubusercontent.com/20047007/103421081-cb4d2280-4b57-11eb-9c49-ba9cc4be64b2.png)


I'm still not sure whether 1.8.19 should work.

I'll backtrack to double check what I actually built.  I had to install gnu-grep to build HDF5EOS.  I'll try fresh build and report back.

**Comment by hkershaw-brown** [comment]
Checkout the `make check` fail for hdf5 1.10.7

````
Check file ../src/.libs/dlname=libhdf5.103.dylib'    testlibinfo.sh: line 57: ../src/.libs/dlname=libhdf5.103.dylib': No such file or directory
 FAILED
Check file ../src/.libs/libhdf5.a                                      PASSED
Check file testhdf5                                                    -SKIP-
***1 errors encountered***
        0.79 real         0.67 user         0.03 sys
`````

../src/.libs/**dlname=libhdf5.103.dylib**': No such file or directory.  I feel like it should be checking for 

../src/.libs/libhdf5.103.dylib which does exist.
