### ISSUE TITLE
text observation converters

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#11]
This is a warning to all who choose to implement a text-to-observation converter.

There are some pretty rough examples in the observation converter directory.
I am trying to clean up a couple to provide good examples, but in the meantime -
please follow the advice in the https://dart.ucar.edu/pages/Observations.html#obs_seq_overview
section "Data Sources and Formats"

**Comment by hkershaw-brown** [comment]
believe this has been put in to the documentation at https://docs.dart.ucar.edu/en/latest/guide/creating-obs-seq-real.html
