### ISSUE TITLE
precomputed forward operator I/O

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#115]
I think the support for precomputed forward operators could be/should be revisited. There is a little 'technical debt' that muddies that waters when reading the code.  The observations/forward_operators/DEFAULT_obs_def_mod.F90 has  `read_obs_def` and `write_obs_def` routines that are responsible for the I/O. I'll include the current write block first:

```
! obs_def%write_external_FO should only be true for program 
! actually WRITING the external data.  When running DART
! obs_def%write_external_FO should be false and no metadata will be written
! Also want obs_def%write_external_FO to somehow be true when this called from
! the obs_sequence_tool program
if ( obs_def%has_external_FO .and. obs_def%write_external_FO ) then
   if ( .not. allocated(obs_def%external_FO)) then
      call error_handler(E_ERR, 'write_obs_def', &
         'obs_def%external_FO not allocated but writing was requested.', &
         source, revision, revdate, text2='observation type '//trim(get_name_for_type_of_obs(obs_def%kind)))
   endif
   if (is_ascii) then
      write(ifile, 12) obs_def%ens_size, obs_def%external_FO_key
      write(ifile, *) (obs_def%external_FO(ii), ii=1,obs_def%ens_size)
   else
      write(ifile)    obs_def%ens_size, external_prior_code
      write(ifile)    (obs_def%external_FO(ii), ii=1,obs_def%ens_size)
   endif
12  format('external_FO', 2i8)
endif
```

First ... if its ASCII, the last item on the first record is the `obs_def%external_FO_key`.
It's a bit convoluted, but I understand why the binary version does not write the character string and only has two items rather than the same number as the ASCII record. However, the binary version writes out `external_prior_code` instead of `obs_def%external_FO_key`.  I don't think it really matters, because the `read_obs_def` routine simply throws away that piece of information if read as binary.

I do not understand why the binary version does not use the `obs_def%external_FO_key`. 

```
! We need to see whether there is external prior metadata.
! If so, we need to read it in, but that doesn't necessarily mean
! the precomputed FO will acutally be used for that particular obs_type
time_set = .false.
obs_def%write_external_FO = .false.  ! Always false when actually running DART
if (is_ascii) then
   read(ifile,fmt='(a)') string
   if (string(1:11) /= 'external_FO') then
      ! no metadata, we really just read the time.
      backspace(ifile) ! go back to previous line to prepare to read time
      obs_def%has_external_FO = .false.
   else ! we have a precomputed FO
      read(string, *) header_external_FO, obs_def%ens_size, obs_def%external_FO_key
      ! FIXME: remove this if * works ok
      !read(string, FMT='(a11, 2i8)') header_external_FO, obs_def%ens_size, obs_def%external_FO_key
      if ( .not. allocated(obs_def%external_FO)) allocate(obs_def%external_FO(obs_def%ens_size))
      read(ifile, *) (obs_def%external_FO(ii), ii=1,obs_def%ens_size)
      obs_def%has_external_FO = .true.
   endif
else
   read(ifile) secs, days
   if ( days /= external_prior_code ) then
      ! no metadata, we really just read the time
      ! can't use backspace on a binary file.
      obs_def%time = set_time(secs, days)
      time_set = .true.
      obs_def%has_external_FO = .false.
   else ! we have a precomputed FO
      counter = counter + 1
      obs_def%ens_size = secs
      obs_def%external_FO_key = counter
      if ( .not. allocated(obs_def%external_FO)) allocate(obs_def%external_FO(obs_def%ens_size))
      read(ifile)    (obs_def%external_FO(ii), ii=1,obs_def%ens_size)
      obs_def%has_external_FO = .true.
   endif
endif 
```

The binary read reads a record with two items ... if there is no precomputed forward operator, these items are the seconds and days of the observation, if there IS a precomputed forward operator it is the ensemble size and the 'disposable' item instead of the `obs_def%external_FO_key`, which is set to the `counter` value.   It seems to me the key value will be different if we read or write the observation in binary or ASCII. I don't know why we would want to do that.

**Comment by nancycollins** [comment]
hi tim -

this code has to work even if the user doesn't set this obs type to be assimilated or the FOs used.  so if there is a FO block following the 2 numbers, it has to read it even if not used.  obs_def%external_FO won't be set in that case.  so the code is on its own here.  it sets the 'days' number to -123, which is illegal for a normal date.  that is how it knows that this is not a valid timestamp.  

it can't use the key values since they are 1,2,3 which are perfectly valid dates and you can't tell them from a timestamp.

the key value is only useful for debugging after the fact.  it's discarded on read and regenerated based on what obs are being used in this run.  i think the binary didn't have another number available to store the key, and so craig punted on it.  it's hardly used, in my experience, and binary files are hard to "browse" anyway.  so if you need to debug something you're probably already outputting ascii.

but given your confusion, it certainly needs more comments around this code.  if you want to chat about this, i'm happy to do a video call.

**Comment by timhoar** [comment]
I understand that the code has to work even if the user doesn't set the obs_type. You are saying you are using the `external_prior_code` (-123) as the flag to indicate that the record is actually the header of a precomputed forward operator metadata block ... fine. The ASCII version should do the same. Not sure what functionality is intended to be provided by `external_FO_key` ... other than to indicate that the next record is something different.  The fact that it has two separate values implies there are two actual uses ... which I do not believe is the case.

**Comment by nancycollins** [comment]
the ascii version writes a text identifier which is consistent with the other items in an ascii obs_seq file.  it also helps with people reading the file.  so the pseudo-date hack isn't needed and would be confusing, i think. 

writing the key is consistent with all the other forward operator code which has a metadata block - it is the per-type key which was used during the last assimilation.  if you put in a print statement to debug a forward operator and printed out the per-type key and then went to look in the obs_seq.out or obs_seq.final you could use that key number to identify this obs.  

yes, it's missing in the binary format but if you're looking at per-type keys you have to write ascii.  i think that's a reasonable compromise, especially for a feature of the system that isn't heavily used.  (craig, roms, and maybe now chris - that's all i know of over the entire user base that have used externally computed FOs.)  

i imagine you could go back and add the key somehow to the binary format but then existing files would no longer be compatible.  too much work for too little payoff?
