### ISSUE TITLE
developer tests logging

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#121]
The `developer_tests/test_dart.csh` script launches a bunch of `run_tests.csh` scripts throughout the project. The run-time output from these is cluttered and it is hard to check to see what has failed and what has succeded. When compared to the output from previous tests, it would be nice to know if things got better or not.

I propose flagging the error messages with a datestamp, but not the successes.

This will highlight a difference in status ... and will continue to highlight all failures.

**Comment by hkershaw-brown** [comment]
believe this was fixed in https://github.com/NCAR/DART/pull/122
