### ISSUE TITLE
sampling error correction file documentation and handling

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#123]
There are several/many files that reference things like
```
set SAMP_ERR_FILE = ${DARTROOT}/system_simulation/final_full_precomputed_tables/final_full.${num_instances}
```
which is not true anymore.
Furthermore, we should be referencing one of these:
```
0[1093] cisl-minnetonka:~/git/DART_development % find . -name "*ampling*nc"
./assimilation_code/programs/gen_sampling_err_table/work/sampling_error_correction_table.nc
./assimilation_code/programs/system_simulation/work/sampling_error_correction_table.Lanai.nc
```

**Comment by hkershaw-brown** [comment]
why are there two directories with sampling error tables?

`assimilation_code/programs/gen_sampling_err_table/gen_sampling_err_table.f90`
looks like a netdf version of 
`assimilation_code/programs/system_simulation/sampling_error.f90`

The `sampe_mean_var` and `comp_correl` in the non-netcdf version are digits12 vs r8.

**Comment by nancycollins** [comment]
anything under system_simulation is jeff's research and not used by other dart programs.  you could discuss removing that directory from the public repo with him.  

the run-time sampling error tables currently used in dart were re-generated by the netcdf program several years ago for most of the common ensemble sizes.  this program is available to generate tables for any additional ensemble sizes that are needed.  the values are not expected to be bitwise with early versions of this feature which used ascii files, one per ensemble size.

**Comment by jlaucar** [comment]
Nancy and Helen are both correct. The netcdf table generation and table
were implemented by Nancy to replace an earlier facility that generated
tables in ascii for individual sizes. The system_simulation directory
includes a variety of other sampling error games and is mentioned as the
source for code in several earlier publications. For now, the code should
probably stay where it is, so I guess there's not any more harm in letting
the duplicate tables hang around? DART complains if SEC is used without a
table in the work directory and points people to the NetCDF table.
