### ISSUE TITLE
parameters for inflation flavor 

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#132]
In adaptive_inflation_mod there are 6 (0-5) flavors of inflation.  Really 5 flavors because 1 has been deprecated.  I can't count to six, so suggest that the integers are replaced with parameters. 

The namelist options for inflation flavor are in filter_mod. So filter_mod can access and change, for example, `inf_initial` independently of the inflation handle: `inflate_handle%inflate`

Documentation note: the adaptive_inflate_mod.html only mentions flavors 2 and 3.

**Comment by nancycollins** [comment]
i agree with this.  inside the fortran code, named parameters would make things clearer.  for namelists, they can be treated like calendar types -- specified as a character string (since namelists don't know about numeric parameters) and then parsed and turned into an integer/named parameter in the code that reads/checks the inflation namelist values.

**Comment by hkershaw-brown** [comment]
Linking pull request 116 to this issue. 

Pull request 116 is an example where inf_initial is being accessed in filter, without going through the inflation mod.

**Comment by hkershaw-brown** [comment]
Nancy comment from pull request https://github.com/NCAR/DART/pull/136

a comment on namelist integers that are being proposed to change to strings. (e.g. filter kind, inflation flavor, calendar type (already done), etc). i'd suggest NOT doing it like this code does it.

i'd declare the namelist variable to be a string, always. after reading the namelist, i'd call a common utility routine that uses read() to try to read an integer from the string. if it succeeds, that's the integer. if it fails, then the calling code can convert the string into an integer using a select() statement that's specific to that module. alternatively, the calling code could construct an array of strings and pass that into the utility routine, and the utility routine could do the matching and always return both the integer and matching string (taking care of case, white space, etc).

if integers are found in the namelist, this new routine could at some point start printing a 'deprecated feature' message to encourage people to convert to strings, but in the meantime it should be fully backwards compatible for users. we might have to change the code to make the namelist variable a string and possibly redefine a separate integer version inside the code but that's under our control.
