### ISSUE TITLE
Karspeck et al. (2013) is not listed on the Publications.md page

### ISSUE THREAD

**Issue by johnsonb-ucar** [NCAR/DART#134]
The article is present on [Opensky](https://opensky.ucar.edu/islandora/object/articles%3A12963) but is not listed on the DART publications page.

**Comment by hkershaw-brown** [comment]
For the future, is it possible to open sky with a query to give all the DART publications?  

 GET open sky "dart author, dart author2 ..."
   
Is it too naive to think we can do this with opensky?

**Comment by johnsonb-ucar** [comment]
I'm not sure if I'm interpreting this incorrectly. So here's an example: I have three publications in OpenSky that don't use DART. Would that prohibit us using a query?

**Comment by timhoar** [comment]
I have long advocated that OpenSky provide metadata that would facilitate queries related to topics rather than simply author or title.
For a decade now ... 'it has been coming' ...

**Comment by hkershaw-brown** [comment]
@johnsonb-ucar I think it just means a more restrictive query. 

You can pull up publications by Lab/Program.  I just tried DARES:
 https://osws.ucar.edu/service/admin

**Comment by hkershaw-brown** [comment]
original issue fixed by https://github.com/NCAR/DART/pull/137

moved this opensky discussion to issue #140.
