### ISSUE TITLE
Using opensky for publications?

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#140]
is it possible to query opensky with something sensible and display the results on dart.ucar.edu

Original discussion in issue https://github.com/NCAR/DART/issues

Note, labeled this as 'back burner'.  Very low priority

**Comment by johnsonb-ucar** [comment]
I scanned the Publications page and it seems like there's a 3:1 ratio of DART publications with NCAR staff to DART publications without NCAR staff. Only publications with NCAR staff will show up in OpenSky. I don't think this precludes populating the publications page using query results. It just makes it slightly harder.
