### ISSUE TITLE
compiling multiple models/ multiple converters at once with local obs_kind_mod and obs_def_mod

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#141]
Back burner issue: 

At the moment, 
````
obs_kind_mod.f90 
obs_def_mod.f90
````

are created in 
````
assimilation_code/modules/observations/
observations/forward_operators/
````

Having local obs_kind_mod.f90 and obs_def_mod.f90 created in the work directory would let you compile multiple models/multiple converters at once. 

Is this important for users?  No not really. Maybe for debugging coupled models if the different models have different obs_def files and/or different quantity files. 

It would let you run all quickbuild.csh scripts simultaneously which would speed up testing. 
Note you could find&replace in path_names and input_nml to run quickbuild.csh simultaneously for testing.

**Comment by nancycollins** [comment]
sounds brilliant.  also location_mod.f90 would need to be local.

**Comment by hkershaw-brown** [comment]
compiling everything at once then checking error codes:
https://github.com/hkershaw-brown/DART/tree/compile_all/compile_everything/quickbuilds
