### ISSUE TITLE
lorenz 96 obs_seq.out - does this need to be in the repo?

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#146]
Does this file need to be under version control?  It is about 6.6MB
This issue came up because I accidentally commited changes to obs_seq.out in pull request 136. 
running with gfortran vs intel makes changes to every line of this file.

**Comment by hkershaw-brown** [comment]
The top 10 largest objects the DART repo.  

All sizes are in MB. The pack column is the size of the object, compressed, inside the pack file.

| size | pack | SHA                                      | location                                                                         |
|------|------|------------------------------------------|----------------------------------------------------------------------------------|
| 47   | 26   | 8234e8c620de298999c10e717b53ceb1da275f5d | models/gitm/testdata2/3DUSR_t110311_204500.bin                                   |
| 11   | 4    | 8210190c5747d45193b24baec9dd88c97b506a61 | models/lorenz_04/work/filter_ics                                                 |
| 10   | 4    | 52a9201c5b1851778c80848d6122baa65b1301fb | models/lorenz_04/work/filter_input.cdl                                           |
| 10   | 9    | cc309eff845656c9a68b81c1112466e4627dfeca | docs/DART_LAB/presentation/DART_LAB_Section01.pdf                                |
| 10   | 9    | 01dac4f0ac20cbfe3cb84227641ac199df950d24 | DART_LAB/presentation/DART_LAB_Section01.pdf                                     |
| 10   | 9    | cb6f156bd6b80dab08cadc482ab0bedd8e357f57 | DART_LAB/presentation/DART_LAB_Section01.pdf                                     |
| 9    | 9    | 7adaed88c7c8bc2451e8f005bce370fc0fa34c18 | models/ROMS/doc/ROMS_kernel.pptx                                                 |
| 9    | 8    | 848b7c3487bdcaf1ad3cb0f1d26e1feccbec47ce | models/am2/work/fv_rst.res.nc                                                    |
| 9    | 4    | f1d361d0cf25fbb72280e695682a1d961a976996 | observations/obs_converters/ROMS/data/wc13_ini.nc                                |
| 9    | 5    | 698b62ffbd96195f2a4a96eb8e36d83f30b279f1 | models/am2/work/atmos_tracers.res.nc                                             

Size may not be the only factor to consider.

**Comment by timhoar** [comment]
To a certain extent, the die is cast. If they have been pushed to GitHub ... done.
To remove them from the repo (and similarly in everyone elses forks and clones) is simply not feasible, as far as I know. Does anyone know of a way to do this? Everything I've read (2+ years ago) makes me think this is not possible.
