### ISSUE TITLE
svn keyword detritus

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#151]
There are many programs/modules that have stale svn keywords that are now uninformative and may be misleading.
The 'source' keyword should reflect the unique program/module name, the 'revision' and 'revdate' keywords should be set to an empty string and/or removed from the calls to `error_handler()`

**Comment by timhoar** [comment]
I am having a difficult time trying to automate the replacement of
```
character(len=256), parameter :: source   = "$URL$"
character(len=32 ), parameter :: revision = "$Revision$"
character(len=128), parameter :: revdate  = "$Date$"
```
with something useful.  Between the dollar signs and the quotes, I cannot get the sed syntax to work correctly.
If one assumes the desired replacement for `"$URL$"` is contained in the a variable  $FILE, it gets a bit more convoluted.

Any regex magicians willing to help?

**Comment by nancycollins** [comment]
note that pull request #156 addresses this issue for only part of the files in the repo (intentionally).  so it's not ready to be closed until the rest of the files are updated.
