### ISSUE TITLE
Preemptively translate DART HTML documentation before pandoc conversion to reStructuredText

### ISSUE THREAD

**Issue by johnsonb-ucar** [NCAR/DART#155]
DAReS staff have been using [pandoc](https://pandoc.org/) to convert the DART documentation from HTML to other markup formats such as markdown and reStructuredText.

The documentation conversion has been slow, because the files output by pandoc must often be edited by hand to clean up conversion artifacts. This is because pandoc has a specific set of syntax elements that it represents in its [abstract syntax tree](https://pandoc.org/MANUAL.pdf).  This set of syntax elements limits what an output document can be composed of -- e.g. titles, links, lists, code, literal strings, references, etc. -- and DART's existing HTML documentation is composed of a much broader collection of idiosyncratic expressions that pandoc isn't equipped to handle.

For example, when a FORTRAN namelist is described in the documentation it is wrapped in a div with a namelist class. Pandoc doesn't have a corresponding syntax expression for such a div, thus the conversion is lossy and the resulting document always contains conversion artifacts.

The key to using pandoc to convert DART documentation from HTML to reStructuredText is to preemptively translate DART's idiosyncratic expressions into a subset of syntax expressions that pandoc is capable of understanding.

Python's [Beautiful Soup](https://www.crummy.com/software/BeautifulSoup/) library is well-equipped for this preemptive translation. It can be used to create functions to handle specific types of idiosyncratic expressions. Since there are many such types of idiosyncratic expressions, DAReS staff will track the progress of the software development in the project associated with this issue.

The actual python scripts that parse the HTML are stored in this repository:

https://github.com/johnsonb-ucar/beautiful-soup

**Comment by timhoar** [comment]
The (new,converted) prototypes are available at 
[https://dart-documentation.readthedocs.io/en/latest/](https://dart-documentation.readthedocs.io/en/latest/)
