### ISSUE TITLE
potential duplicate obs_assim_count.f90

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#157]
We have the following two files:

- assimilation_code/programs/obs_assim_count/obs_assim_count.f90
- assimilation_code/programs/obs_utils/obs_assim_count.f90

Are they identical, can be consolidated?   Not looked into it at all ...

**Comment by hkershaw-brown** [comment]
Not identical, both appear to be in use. 

````
hkershaw@cisl-fisher DART (Manhattan) $ grep -rn assimilation_code/programs/obs_utils/obs_assim_count.f90 .
./observations/utilities/oned/path_names_obs_assim_count:25:assimilation_code/programs/obs_utils/obs_assim_count.f90
./observations/utilities/threed_sphere/path_names_obs_assim_count:24:assimilation_code/programs/obs_utils/obs_assim_count.f90

hkershaw@cisl-fisher DART (Manhattan) $ grep -nr assimilation_code/programs/obs_assim_count/obs_assim_count.f90 .
./assimilation_code/programs/obs_assim_count/work/path_names_obs_assim_count:24:assimilation_code/programs/obs_assim_count/obs_assim_count.f90
````

**Comment by hkershaw-brown** [comment]
I'm assuming there is not supposed to be two versions of this file, labelling as a bug until otherwise informed.

**Comment by nancycollins** [comment]
agreed - bug. my fault.  at one point i dumped a bunch of my own obs utilities in obs_utils because i didn't know if they deserved to have their own directories or if they were just useful to me. 

if you want i can try to reconcile the two versions.  where do you prefer the unified version should live?  in obs_utils or its own directory?

**Comment by nancycollins** [comment]
i reviewed the two versions.  the one in **obs_utils** has more features and is 100% a superset of the one in the **obs_assim_count** directory.   

choice 1: remove the assimilation_code/programs/obs_assim_count directory and all files below it;  update all pathnames to point to assimilation_code/programs/obs_utils/obs_assim_count.f90

choice 2: replace assimilation_code/programs/obs_assim_count/obs_assim_count.f90 and obs_assim_count.nml with the version in programs/obs_utils, add a work subdir, fill it with quickbuild, mkmf and pathnames files.  remove obs_utils/obs_assim_count.f90 and any related pathname files in that work directory.  update all pathnames files to point to assimation_code/programs/obs_assim_count/obs_assim_count.f90

the obs_utils dir contains these small obs_seq tools:

- create_obs_grid.f90 
- obs_assim_count.f90
- obs_data_denial.f90
- obs_info.f90
- obs_remove_dups.f90
- obs_sort.f90
- obs_timejitter.f90

all things being equal, i'd suggest choice 1 unless you also want to split these out into their own directories under assimilation_code/programs.  most of these will be obsolete once we change obs file formats anyway.

**Comment by kdraeder** [comment]
I'm documenting the assimilation_code/programs directory and wonder whether
this redundancy was resolved anywhere.  It's still in the
sphinx-documentation branch.
Thanks,
Kevin

**Comment by nancycollins** [comment]
i'd recommend resolving this by implementing choice 1 in my comment from march 12.
