### ISSUE TITLE
create_ensemble_from_single_file allocating a 'model_size' variable

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#18]
filter_mod:create_ensemble_from_single_file()   has a bug creating an ensemble from a single file when the single file is allowed to have MISSING values. The logic is supposed to be

1. record the location of the missing values
1. copy the single member to all the other members
1. add perturbations
1. ensure the new members have missing values in the same place.

At present, the array recording the locations of the missing values is allocated to the wrong length.
Allocating it to the "correct" 'model_size' is the wrong approach - we work with some models that are too big. Another approach is needed ... working on one variable at a time, perhaps ...

**Comment by timhoar** [comment]
Allocating it to the 'model_size' is the wrong general approach. However, since this is in filter_mod.f90, it is possible to allocate an array that is simply the size of the elements that have been distributed to that task. That should not be a problem in general. This has been done in PR 86 on the development site. When that gets approved, the bugfix will be committed here.

**Comment by hkershaw-brown** [comment]
this fix was committed to the 
in commit 650daf09319c93dddc3301c3fbc76139033bd15d
