### ISSUE TITLE
Update content of camX readme.rst files

### ISSUE THREAD

**Issue by kdraeder** [NCAR/DART#182]
Date: 2021-3-12

Related Issues: This issue was prompted by #111 and partially solves it.

### Overview:
Update readme.rst file(s) to
+ document cam-fv, and maybe CESM and a new cam-se
+ make the content reflect the current CESM and DART environments,
+ use a template that's consistent with other models'

### Terminology:
**cam-se** is the spectral element dynamical core of CAM.
It's defined on a cubed-sphere grid, in contrast to the
**cam-fv** finite volume core, which is defined on a "rectangular" latitude-longitude grid.
They use the same vertical structure and "physics"
**CESM**   The software framework in which cam-fv, cam-se, or other models such as POP
are defined.  As a model in DART it represents assimilations using model states
containing variables from > 1 component, such as temperature from CAM and salinity from POP.

### Functional Specification:
The readme(s) will provide context for understanding CAM+DART assimilations
and how to set them up and run them.
Most of the details of setup are contained in the shell_scripts/Version/\*setup\* scripts
and will not be described in the readmes.

### Technical Specification:
I'll use the POP/readme.rst (@johnsonb-ucar 's recommendation)
from sphinx-documentation (@hkershaw-brown 's) as the template.
The html -> rst conversion of cam-fv/readme.rst has been done,
but the content might benefit from being more consistent with POP's.

### Open Issues:
One strategy question is whether there will be a CESM/readme.rst,
which contains an overview of assimilation with CESM components,
and which can be referenced by the component readme.rst files.
The CESM readme would describe
+ cross-component (strongly coupled) and multi-component (weakly coupled) modes,
+ running in multi-driver mode
+ DATM capabilities
+ cam-fv and -se share DART code, which could be described here, or in the cam-X readmes
+ ...?
This might prompt additional updates of the POP, clm, and cice readmes.

### Non Goals:
Ignore the advanced scripting and workflow of the CAM6+DART Reanalysis.

**Comment by hkershaw-brown** [comment]
looks like a good plan Kevin.

**Comment by kdraeder** [comment]
Since it should accelerate this process, I installed atom in order to
quickly see the rendered versions of the rst files.
I open a file in atom, then select the tab Packages:Markdown Preview:Toggle
Preview.
That opens a new tab which has a badly rendered version of the rst.
Some rst syntax that doesn't work includes
| supposed to be item 1?
| supposed to be item 2?

.. container:: indent1     shows up explicitly
The table packaging doesn't work
+----------+
| Contents|
+========+

Is there a widget in atom that I need to activate?
Their search doesn't find anything about restructured text or rst.

**Comment by hkershaw-brown** [comment]
welcome to the world of ~~overly completed~~ customizable  text editors

Packages -> Settings View -> install packages

````
   language-restructuredtext
   rst-preview-pandoc
````

And install pandoc.  I used the installer from here: https://pandoc.org/installing.html

In Atom, 
   control + shift + e opens the preview. 

![Screen Shot 2021-03-19 at 3 29 29 PM](https://user-images.githubusercontent.com/20047007/111844080-ecf0b700-88c7-11eb-82de-0edcb7dabacc.png)

**Comment by kdraeder** [comment]
Thanks.  language-... installed fine, but ***@***.*** failed
both before and after I installed pandoc.
The first error message is

c++: error: unrecognized command line option '-stdlib=libc++'


However, I tried rst-preview-pandoc, which did install.
But now the Markdown toggle does nothing visible.

**Comment by kdraeder** [comment]
Oh yes, it's ctrl-shft-e now, not -m.

**Comment by kdraeder** [comment]
Atom refused to close on Friday.  I tried a half-dozen things before finally manually turning off my Mac.
This is a not uncommon problem, with several possible hack fixes.  I tried the 
$ atom --clear-window-state readme.rst
method, but atom is not found today.

I opened atom via the Finder, opened my readme.rst, and tried to render it with CTRL-SHIFT-e, but got 
"pandoc' could not be spawned. Is it installed and on your path? 
 If so please open an issue on the package spawning the process."
I installed pandoc last Friday and again today,
but the message still pops up and the rendering doesn't happen.

Searching for 
`'pandoc' could not be spawned. " atom "rst-preview-pandoc" `
yielded
[https://wiert.me/2016/04/28/restructuredtext-notes-rst-file-extension/](https://wiert.me/2016/04/28/restructuredtext-notes-rst-file-extension/)
which led to 
[https://github.com/jagregory/atom-pandoc-preview/issues/14#issuecomment-70392963](https://github.com/jagregory/atom-pandoc-preview/issues/14#issuecomment-70392963)
Atom is not in my path, so  
$ vi `which atom` 
didn't work.  Eventually I found 
/Applications/Atom.app/Contents/Resources/app/atom.sh 
(instead of atom).  I had to 
$ setenv PATH /Applications/Atom.app/Contents/Resources/app:$PATH
in order to be able to 
$ atom.sh
which seems to work.  (python is not necessary).  
Atom:Quit atom 
seems to work, so this is fixed for the time being.

**Comment by kdraeder** [comment]
Also, those fixes only fix the rst preview when atom.sh is started from the command line.
Applications:atom yields the pandoc error message.  Also, if atom is started by a system restart
the same thing happens.  The location of pandoc (/usr/local/bin) is in my path in XQuartz windows,
so I don't know why it isn't found.

**Comment by kdraeder** [comment]
A content question!
Older versions of CAM and CCSM (precursor to CESM) have files that were useful stored in
http://www.image.ucar.edu/pub/DART/CAM/
My impression is that image.ucar.edu will disappear, but the pub/DART site has lots of  content,
that's more current than /CAM, so that will be moved/redirected somewhere.
I have email from Tim saying that the destination is https://dart.ucar.edu/pages.
No universal redirect is possible, so we need to select the pieces that will be redirected.
Should pub/DART/CAM be one of them?
(I/we seem to have decided not to rescue CAM4 reanalysis restart file sets from the HPSS,
 so these would seem even less useful.)

It's somewhat related to pub/DART/Release_datasets/
which has a "large files" file for each release.

pub/DART/Reanalysis should be saved (CAM6+DART multiyear profiles diagnostics).

The cam-fv/readme.rst also references observation sample files in pub/DART/Obs_sets/.
They aren't the latest, but may still be useful for helping people get started.


Also, https://github.com/NCAR/DART/tree/Manhattan/docs/pages/CESM_DART_guidelines.md
will need to be updated from my new models/CESM/readme.rst and doc/setup_guidelines.rst,
unless the rst will be used as a source for some process that generates a replacement
for the md file.
The github.com/NCAR/DART/blob/sphinx-documentation  versions of those files will/should
be updated when I push the changes in my Manhattan-cam-docs repository (cam-readme-update branch).

**Comment by kdraeder** [comment]
Sorry they look so broken.  They looked reasonable as rendered in atom.
And the vim syntax didn't pick up on the spacing errors either.

Do I need to install and run sphinx on these before I push them?

Kevin

**Comment by hkershaw-brown** [comment]
They are not that broken, it is just Sphinx complaining.  

I'll send you a makefile so you can build locally if you want.  Let me know if you want me to go ahead and fix the "malformed table" and headings.

**Comment by hkershaw-brown** [comment]
I believe this is done since https://github.com/NCAR/DART/pull/195 was merged.
