### ISSUE TITLE
obs_info does not support identity observations

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#186]
If there are identity observations in the file being run through obs_info.f90 the program crashes.

```
At line 196 of file ../../../assimilation_code/programs/obs_utils/obs_info.f90
Fortran runtime error: Index '-1' of dimension 1 of array 'oinfo' below lower bound of 1

Error termination. Backtrace:
#0  0x1055efd3e
#1  0x1055f05dc
#2  0x1055f0b4f
#3  0x104d48ba8
#4  0x104d4b787
```

**Comment by mgharamti** [comment]
Perhaps, this is a feature. I've used obs_info for real observations only and was quite useful. It could be extended maybe to support identity obs though I don't know how much people would make use of it.

**Comment by timhoar** [comment]
Whatever it does, it should not bomb. If it skips them - fine - if it encounters one and exits gracefully - fine - if it just counts up all identity obs and reports the aggregate number - fine.

**Comment by nancycollins** [comment]
i've changed the code to count identity obs.  what input obs_seq file were you using for testing?

**Comment by timhoar** [comment]
I just used the lorenz_63 observation sequence file ... had to paste in the obs_info namelist block.

**Comment by nancycollins** [comment]
see [pull request #189](https://github.com/NCAR/DART/pull/189)
