### ISSUE TITLE
Web pages that need porting to .rst 

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#187]
This issue is to track old website content, to ensure that content that needs to be moved to either the new website or the sphinx documentation is moved. 

There is a much larger project to review the html->rst conversion, followed by reviewing & updating the actual page content. 

Old website temporarily available at https://ncar.github.io/old-web
You can take a look at the https://github.com/NCAR/old-web for the markdown (this is currently the same as the master branch [docs directory](https://github.com/NCAR/DART/tree/master).  

Here is the content from the docs/pages:  

- [x] About_Us.md (this is on the web)
- [x] CESM_DART_guidelines.md (on [docs](https://dart-documentation.readthedocs.io/en/latest/models/CESM/doc/setup_guidelines.html?highlight=CESM))
    - [ ]  The docs version is converted from https://github.com/NCAR/DART/blob/master/models/CESM/doc/setup_guidelines.html which is different from CESM_DART_guidelines.md
- [ ] Diagnostics.md. (partly on docs)
   - [ ] matlab setup (diagnostics/matlab/startup.m)
   -  There is a link in the DART Tutorial [Configuring Matlab® for netCDF & DART](http://www.image.ucar.edu/DAReS/DART/DART2_Documentation.php#configure_matlab) which is _Forbidden_
- [x] Getting_Started.md (on docs). There is a lot of content in this page.
   - [x] system requirements
   - [x] Fortran90 compiler
   - [x] Locating netCDF library
   - [x] Downloading DART
   - [x] Compiling DART
   - [x] Verifying Installation
       - [x] missing the graphics: https://ncar.github.io/old-web/pages/Getting_Started.html#verify fixed: bf30c668c6c549a28848df6c9fd851f3fe15eaa7
   - [x] Contributing to DART
   - [x] What is DA
   - [x] What is DART
   - [x] How do I run DART with my model
   - [ ] How do I add my observations to DART (this does not have the new preprocess method described in [obs_def_mod.html](https://dart-documentation.readthedocs.io/en/latest/observations/forward_operators/obs_def_mod.html)
   - [ ] matlab setup (diagnostics/matlab/startup.m) 
- [ ] Miscellany.md (this is faq)
- [ ] Models.md (there is a models/README.rst that lists the supported models. Need to merge models.md into models.rst)
- [x] Observations.md - some of this is out of date, for example the default for preprocess is to overwrite obs_def_mod.f90 and obs_kind_mod.f90
- [x] Presentations.md on the [web](https://dart.ucar.edu/presentations/). TODO: better navigation to find this
- [x] Publications.md on the [web](https://dart.ucar.edu/publications/). TODO: better navigation to find this
- [x] Radiance_support.md in pull request: https://github.com/NCAR/DART/pull/188
- [x] Research.md on the [web](https://dart.ucar.edu/research/)
- [x] Tutorial.md on the [web](https://dart.ucar.edu/tutorials/) and in the docs.
- [ ] ~~WRF_DART_guidelines.md~~ - this is out of date - it talks about dart-to-wrf
- [ ] ~~api.md~~ Not used
- [x] dart_lab.md on the [web](https://dart.ucar.edu/tutorials/dart-lab/) and in the docs
- [x] dart_mpi.md (docs) partly rewritten: [mpi](https://dart-documentation.readthedocs.io/en/latest/guide/mpi_intro.html)
- [ ] ~~random_seq_mod.md~~. I don't think there was a link to this page. There is random_seq_mod in the docs
- [x] release.md on docs
- [x] support.md on website
- [ ] ~~time_manager_mod.md~~ I don't think there was a link to this page.  There is time_manager_mod in the docs

#### md files in the repo (but not in the docs directory):
- [ ] build_templates/README.md
- [x] models/wrf/tutorial/README.md
- [x] models/README.md (~~there is a note in this file: "This document is really quite out-of-date. TJH 22 Apr 2020~~" fixed: 7c2f52dfa38160d2bf39c0984828f80ecc9dc583)
- [ ] models/FESOM/diagnostics/script/README.md
- [ ] models/wrf_hydro/python/experiment/README.md
- [ ] models/wrf_hydro/hydro_dart_py/README.md

Pull request https://github.com/NCAR/DART/pull/190
- [x] observations/obs_converters/GOES/README.md
- [x] observations/obs_converters/README.md
- [x] observations/obs_converters/GMI/README.md
- [x] observations/obs_converters/MPD/README.md
- [x] observations/obs_converters/AIRS/README.md

Incorrect documentation that needs to be removed:
- [x] Manhattan Release notes from (Manhattan_getting_started.rst).  
- [x] bgrid_solo (this is not incorrect, but should not be part of the dart .rst documentation)
- [x] [Hints for porting a new model](https://dart-documentation.readthedocs.io/en/latest/models/README.html#hints-for-porting-a-new-model-to-dart) is marked 'out of date'. Fixed: 7c2f52dfa38160d2bf39c0984828f80ecc9dc583

Duplicates
- [ ] Observation Converters is in twice 
  - DART/observations/obs_converters/README.rst
  - guide/pages/Observations.md. (converted to guide/creating-obs-seq-real.rst)

For previous releases:
- [x] list on the history page, but do not have the release notes in the .rst docs
- [x] Previous releases .rst not in the doc.   There is a page on the Manhattan Release. - does this need updating/removing?

Missing documentation:
- [x] RTPS from https://github.com/NCAR/DART/pull/179

Weird formatting: _slightly_ less weird with solid background for the table rows. 
- [x] https://dart-documentation.readthedocs.io/en/latest/guide/required-model-mod-routines.html is weird with table wrapping. 
- [x] observations/obs_converters/Ameriflux/level4_to_obs.html
- [x] observations/obs_converters/ROMS/ROMS.html
- [x] observations/obs_converters/SST/SST.html
- [x] theory/readme.html
- [x] models/tiegcm/readme.html

**Comment by hkershaw-brown** [comment]
Note on documentation versions.

The old-website ran from the master branch
The html files are in the Manhattan branch (and the master branch at the moment). 
The rst files are from the master branch, which is the 'latest'.

**Comment by johnsonb-ucar** [comment]
I am working on Diagnostics.md and Observations.md at the moment. It is difficult to commit and push partially converted versions of those two documents, because each document in long, and each contains hyperlinks to sections of the other. I think that I will be able to push a progress update to the sphinx-documentation branch once those two files are converted.

**Comment by hkershaw-brown** [comment]
@johnsonb-ucar  are you also working on any of the other markdown files:

./models/wrf/tutorial/README.md
./models/README.md
./models/FESOM/diagnostics/script/README.md
./models/wrf_hydro/python/experiment/README.md
./models/wrf_hydro/hydro_dart_py/README.md
./observations/obs_converters/GOES/README.md
./observations/obs_converters/README.md
./observations/obs_converters/GMI/README.md
./observations/obs_converters/MPD/README.md
./observations/obs_converters/AIRS/README.md

In particular, the observations/obs_converters README.md files?

**Comment by johnsonb-ucar** [comment]
Nope. I haven't touched any of the obs_converters README.md files.

I am nowhere near editing any of the files you mention in the above comment.

**Comment by hkershaw-brown** [comment]
cool.  There is a lot of documentation.  I'll take a crack at converting

./observations/obs_converters/GOES/README.md
./observations/obs_converters/README.md
./observations/obs_converters/GMI/README.md
./observations/obs_converters/MPD/README.md
./observations/obs_converters/AIRS/README.md

**Comment by johnsonb-ucar** [comment]
Sounds good. I'm almost completely done with Diagnostics and Observations. I should have those committed and pushed today. At that point, I'll update the website triage spreadsheet so we can divide and conquer with the whole team.

**Comment by johnsonb-ucar** [comment]
I updated the website triage spreadsheet in the DAReS team shared Google drive with the title, source rst file and URL of the rendered HTML of each of the pages contained in the Sphinx documentation.

**Comment by hkershaw-brown** [comment]
I made it from line 301 to line 112.   Most of the pages are pretty good!

I'm going on a broken link fixing mission.  Stop me if someone else is already doing this. 

- broken links
- removing tray <T> html tags
- fixing broken tables. 


I put a bunch of notes for "the routine names are in italics, instead of in the code block".   Like this:
![Screen Shot 2021-03-24 at 10 42 46 AM](https://user-images.githubusercontent.com/20047007/112348718-b0d5a180-8c8d-11eb-8988-156f1a40a8b8.png)

I'm not sure what to do about these.  

Some of the tables are super wide, but I think we can change that with a site configuration option to wrap text in tables.

**Comment by hkershaw-brown** [comment]
Note on ./guide/_static/css/custom.css

````
37    "../fonts/Roboto/Roboto-RegularItalic.ttf". 
````

Roboto-RegularItalic.ttf does not exist in guide/_static/fonts/Roboto/

**Comment by hkershaw-brown** [comment]
HK: this afternoon, working on  converting 
  Models.md (there is a models/README.rst that lists the supported models. Need to merge models.md into models.rst)

**Comment by hkershaw-brown** [comment]
Documentation for RTPS was added to filter.html in pull request:
  
   https://github.com/NCAR/DART/pull/179

filter.html looks to have been split into several files in commit: 10d8fd3ed8df2e6da0fa604f35e8a8eb1aa09bab

guide/inflation.rst does not contain the latest changes from https://github.com/NCAR/DART/pull/179

**Comment by hkershaw-brown** [comment]
Let's regroup before any more rewrites.

**Comment by hkershaw-brown** [comment]
Note on Changelog -> CHANGELOG

Don't want the changelog as an rst table.
