### ISSUE TITLE
DART QC = 7 and a failed posterior forward operator - obs_diag bug

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#19]
There is a bug that involves the rare situation when the prior observation is rejected by the outlier threshold and the posterior forward operator fails. DART does not have an error code that covers that situation. The obs_diag program correctly records the prior observation rejection as a DART QC of 7, if the posterior forward operator failed, the obs_diag program (incorrectly) assigned the posterior QC to  DART QC of 4. The correct error code for a failed posterior forward operator is 2, not 4.

Worse, the logic to check for a failed posterior forward operator when the prior was rejected was not implemented correctly in all parts of the code.  **Let me repeat that the statistics for the priors are and have been correct.** Only in rare situations were the posterior statistics incorrect. Since we all know that posterior statistics are not the best metric to begin with, I hope this has not caused you any problems.

Even before 2015, the run-time output and log messages of obs_diag correctly report the number of observations in this situation - see the last line below:
```
 # observations used  :         9600
 Count summary over all regions - obs may count for multiple regions:
 # identity           :            0
 # bad Innov  (ratio) :            0
 # bad UV (wind pairs):            0
 # bad Level          :            0
 # big (original) QC  :            0
 # bad DART QC prior  :            0
 # bad DART QC post   :            0
 # priorQC 7 postQC 4 :            0
```

I am in the process of correcting the logic. Stay tuned for a GitHub pull request to address the issue.

**Comment by timhoar** [comment]
This is development Issue PR 89

**Comment by hkershaw-brown** [comment]
This fix made it into DART::master in pull request https://github.com/NCAR/DART/pull/46
