### ISSUE TITLE
Dependabots alerts for wrf hydro

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#192]
Dependabot alerts for models/wrf_hydro/python/experiment/requirements.txt on the Manhattan branch.

Possible solution:
Have dependabot automatically issue pull requests.

I'm not sure if anyone is using Manhattan wrf_hydro so other solutions:
* dismiss the alerts as 'vulnerable code not actually used'

The alerts are only on default branch (which is Manhattan currently).  The master branch does not contain the wrf hydro requirement file.

**Comment by timhoar** [comment]
I'd like to see the Manhattan branch get updated ... sooner rather than later. When that happens, the requirememnts.txt file goes away and this Issue is moot. 

Are we planning to update Manhattan (9.10.0?) or are we going for a new major release?
