### ISSUE TITLE
menu glyphs for sections with subsections

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#202]
When the (readthedocs) navigation sidebar comes up, there is no indication for which sections have subsections, so unless you click on EVERY section, you never know if there are subsections, if the subsections are relevant to what you're looking for - or ...

AFTER you click on the section - the little square with the plus symbol is there - which is nice - but that should be there from the beginning, in my opinion.

**Comment by hkershaw-brown** [comment]
Screenshot of this behavior:

![before click](https://user-images.githubusercontent.com/20047007/115425659-0d5cab80-a1bd-11eb-91b2-9edf3c196030.png) No +
![after click](https://user-images.githubusercontent.com/20047007/115425667-0e8dd880-a1bd-11eb-99ee-baef4df56840.png) + appears
