### ISSUE TITLE
readme.md, quickstart section needs update

### ISSUE THREAD

**Issue by nancycollins** [NCAR/DART#207]
the very first part of the 'quickstart for the impatient' section needs to be updated, i think.

for 99% of our downloaders we should tell them to simply clone dart, not fork it.  their fork will quickly get out of date and it's more repositories to complicate their workflow.  for collaborators who are going to develop code with us, they can choose to work from a fork if they want.  but these shouldn't be the default instructions.

also, we shouldn't have the "large files" listed there for anything older than lanai, and maybe not even lanai.  there could be a link to 'older files' if someone wants a record of how to get "historical documents".

this section is supposed to be the quickest way to get started with dart.  it should have the minimal info and be the simplest way to get something running.

**Comment by hkershaw-brown** [comment]
note on this: 
there is a downloading [dart section ](https://dart-documentation.readthedocs.io/en/stable/guide/downloading-dart.html)and in [quick-start](https://dart-documentation.readthedocs.io/en/stable/README.html#quick-start) section.  One is fork, one is no fork. 
Also, download instructions in the repo README.md

**Comment by nancycollins** [comment]
part of this issue has been now been addressed (the workflow) by pull request #214 

the large files list still goes into the far past.  also, there is still a README.md and README.rst in the top level dir.  if one can be renamed to index that might be less confusing.

**Comment by hkershaw-brown** [comment]
mostly closed
