### ISSUE TITLE
AIRS/convert_amsu_L1.f90 partial output

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#208]
The observations/obs_converters/AIRS/convert_amsu_L1.f90  has the ability to read multiple input data files but is only writing out the observations in the LAST input file.  The crux of the problem is that the output filename is being opened and closed inside the loop over the input filenames. The program is reading and writing the data correctly for each file, but it is overwriting the same file over and over.

In addition to fixing the bug listed above, there are a couple things that would be nice features to have, so I am listing them here and will outline what I think is the most expedient way to provide the necessary functionality:

- A namelist option should control what happens if the named output file exists - append? overwrite?
- Some recognition of what input file is being read seems appropriate
- A summary of the contents of the observation sequence file being written seems useful ... how many observations, (of each type), etc. ... since this may be more than some people want - perhaps control that with a 'verbosity' namelist option.

Right now the program flow is to:

1. Read the namelist
2. Determine how many input files there are
3. Initialize the amsua structure (`initialize_amsua_netcdf()`)
4. Loop over the input files
   - Read the file into a structure (`read_amsua_bt_netCDF_granule()`)
   - convert the structure to a new  observation sequence (`make_obs_sequence()`)
   - write the observation sequence to the output file (`write_obs_seq()`)
   - destroy the observation sequence so it can be made new in the next cycle (`destroy_obs_sequence()`)
5. Finalize/clean up.

The suggested program flow could be:

1. Read the namelist
2. Determine how many input files there are - and determine an upper bound on the number of observations might be made.
3. If the output file is to be appended:
   - an observation sequence file large enough to hold all the observations must be initialized
   - the observation sequence file must be read
   If the output file is to be created from scratch:
   - an observation sequence file large enough to hold all the observations must be initialized
4. Loop over the input files
   - report which file is being processed
   - Read the file into a structure (`read_amsua_bt_netCDF_granule()` is unchanged)
   - append the structure into the observation sequence - `make_obs_sequence()` cannot create a new observation sequence each time - must use the sequence from step 3 and `add_obs_to_seq()` - one observation at a time. 
5. summarize the sequence (look at `obs_sequence_mod:print_obs_seq_summary()`)
6. write the observation sequence to the output file (`write_obs_seq()`)
7. destroy the observation sequence so it can be made new in the next cycle (`destroy_obs_sequence()`)
8.  Finalize/clean up.

`MADIS/convert_madis_acars.f90` has a good example of Step 3.
`obs_utilities_mod.f90` has a nice routine `add_obs_to_seq()`
`obs_sequence_mod.f90` has a nice routine `print_obs_seq_summary()` which is already called by the AIRS converter (in the `amsua_netCDF_support_mod:add_granule_observations()` routine). 
Perhaps `print_obs_seq_summary()` should be called (again?) at the end. 
Perhaps `add_granule_observations()` should also report which file is the source of the granule?

There are two test files in the (very large 4GB) tarfile we use to test the DART installation:
`/glade/p/cisl/dares/DART_test_cases/test_build_datasets_preprocess.tar`
`AIRS.2019.06.22.236.L1B.AMSU_Rad.v5.0.0.0.G19174110442.nc,
AIRS.2019.06.22.237.L1B.AMSU_Rad.v5.0.0.0.G19174110446.nc`

**Comment by nancycollins** [comment]
looks very good.  

a few small comments:

new #7 - the cleanup is just to be consistent. there is no new "next cycle" in this program.  but it's good to destroy things you've created to have a cleaner program.

new #3, 1  & 3 - these bullet points looks very much the same.   maybe it's clearer if the first mentions 'opening the existing file and using the option of adding more space to it'.  (the open routine for obs_seq has the ability to ask to add more space at that time).  the last bullet point could mention creating/initializing an obs_seq or something. i'm sure that's what you meant but the descriptions aren't as clear.

verbosity:  i very much agree with making a namelist variable about how verbose to be.  i'd suggest it control both the printing the names of the input files being read and the summary of output obs created.  for a single run or a couple small runs that kind of output is really helpful.  but -  for a long, scripted batch run (like when i was generating 10 years of obs for the reanalysis) you have to be very conservative about output.  the log files get huge and if there's a lot of 'this is working normally' type messages then you easily miss 'this doesn't seem right' messages.   i'd make it as terse as possible unless the verbose flag is on.  if the verbose flag is on, then print away!

**Comment by braczka** [comment]
Thank you Tim and Nancy for setting this up.  Your explanation(s) of what needs to be modified seems pretty clear.  Will take a closer look later this week.   Reviewing the file organization with Tim/Helen yesterday was a helpful start, but I will need to revisit before suggesting edits....
