### ISSUE TITLE
remove obs_seq_utilities_mod.f90

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#209]
As far as I can tell,   _observations/obs_converters/utilities/obs_seq_utilities_mod.f90_   is not used by any existing _path_names*_ file.

There are three public routines in it, all of which are in _assimilation_code/modules/observations/obs_sequence_mod.f90_

**Comment by hkershaw-brown** [comment]
mentioned in https://github.com/NCAR/DART/issues/185

**Comment by timhoar** [comment]
I have more of a problem with having many files scattered about unpredictable places ... 
Furthermore, by adding new files - we have to change all the path_names_  files, which is a nuisance.
To the newcomer, I think it makes sense to look in the obs_sequence_mod   for obs_sequence-related stuff.
Why make the fuzzy distinction on what is a 'utility' vs. ?

I say "LUMP EM" ... put them all in one place, easy to find, you might run across something that's useful and not reinvent in ...

**Comment by nancycollins** [comment]
i hate to say that all computer science wisdom disagrees with you.  smaller, single focus modules are easier to maintain and preserve strict interfaces to data structures.   editing path names files happens once and is done.   debugging and separating routines that violate intended access patterns is the price if you don't.

**Comment by timhoar** [comment]
> i hate to say that all computer science wisdom disagrees with you. smaller, single focus modules are easier to maintain and preserve strict interfaces to data structures. editing path names files happens once and is done. debugging and separating routines that violate intended access patterns is the price if you don't.

_So what you're saying is that I'm smarter than all of computer science wisdom_ ... Can we at least put all the modules in the same directory? Why should the obs_seq_utilities_mod.f90 exist in `observations/obs_converters/utilities/` directory when the `obs_sequence_mod.f90` exists in 'assimilation_code/modules/observations/'?

**Comment by nancycollins** [comment]
sure - putting them in the same directory seems like a good suggestion.
