### ISSUE TITLE
TIE-GCM 2.0 issues with DART Lanai

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#21]
Dear DART Team,

I have recently been attempting to get started using TIE-GCM 2 with DART-8.4.1. The main changes that have been made have been incorporating new namelist variables and ensuring TIE-GCM is executed with mpirun (as required by the new version, even in the single processor case).

I’ve been attempting to run the script run_filter.csh (modified version attached) without success. This test is done with obs_seq.out from run_perfect_model_obs.csh and one processor. The first sign that anything is going wrong in the attached output is when I get:
```
mbind: Invalid argument
```
The program filter (which propagates an ensemble of TIE-GCM runs) does continue to run after this point, though seemingly ultimately fails to run TIE-GCM. See L529 onward of the attached file, where the code notices that it has failed to advance the model and produces an error.

[run_tiegcm_assim_gadi.o6872291.txt](https://github.com/NCAR/DART/files/4772244/run_tiegcm_assim_gadi.o6872291.txt)
[run_filter.csh.txt](https://github.com/NCAR/DART/files/4772245/run_filter.csh.txt)
[input.nml.txt](https://github.com/NCAR/DART/files/4772246/input.nml.txt)
[advance_model.csh.txt](https://github.com/NCAR/DART/files/4772247/advance_model.csh.txt)

Is this an error that you are familiar with and do you have any recommendations for fixing it?

**Comment by timhoar** [comment]
I have not seen the mbind problem before ... can you run other commands with the 'mpirun -np 1' syntax?

I think you understand the situation: Essentially filter understands the model is at 146541 120  and needs to be advanced 180 seconds to 146541 300 but the advance_model.csh script is not getting the job done ... it finishes and the model state is still at 146541 120.   The 'dart_to_model' executables (which are serial) look like they are working, which means the next step is to actually run tiegcm. I don't think the mbind problem has anything to do with DART, as much as invoking the parallel executables.

Does tiegcm start up at all?  I'm hoping there may be more of a clue in its run-time output. (tiegcm_out_xxx)

**Comment by gwbowden** [comment]
Thanks for opening this issue. I have had similar results using "mpirun -np 1 ./filter || exit 2" and using "./filter || exit 2" to run the filter program. However, I have previously been successful advancing the model state using "mpirun -np 1 ../tiegcm tiegcm.nml |& tee tiegcm_out_$ensemble_member" in advance_model.csh.

The tiegcm_out_xxx files are created, but are empty.

**Comment by timhoar** [comment]
So now I'm a bit confused. You "... had similar results using `mpirun -np 1 ./filter` ..." yet filter seems to be running - can you clarify what you mean?
As for running `./filter || exit 2`, you had to compile filter without mpi for that ... it certainly _shouldn't_ work like that if you had compiled with mpi. 

I see your job script requests resources: 1 cpu and 8GB of memory. That is not a lot of memory ...
Do you have access to a whole node? Keep in mind that _at_some_point_ the entire model state for all the ensemble members needs to be available to filter - depending on your resolution, this could easily exceed 8GB.

Does your systems group have any advice about one MPI process (filter) running another MPI process (tiegcm) in the same job? Your job script is the 'simple' one, which (may or may not) support this calling sequence.  The `run_filter_async4.csh` is designed to launch an mpi executable (filter), which goes to sleep when it comes time to launch the other mpi executable (tiegcm) and then wakes up when the tiegcm is finished.  It's a bit more complicated, granted, and the communication happens through named pipes, but it has been tested on several platforms and allows two MPI executables to be run in the same job (just not at the same time, naturally).

**Comment by gwbowden** [comment]
To clarify, using the command `mpirun -np 1 ./filter` causes filter to run without starting TIE-GCM producing the output in `run_tiegcm_assim_gadi.o6872291.txt`. The DART programs were compiled using the quickbuild.csh, with the default -mpi flag.

The resources requested may be too low to successfully run TIE-GCM, though should not affect the current problem that the program seems not to start. Nevertheless, I have tried requesting:
#PBS -l ncpus=4
#PBS -l mem=32GB
with similar results. More resources are available if need be, but testing with less reduces the waiting time.

The comments in the script `run_filter_async4.csh` seem to indicate it can be run with `async=2` and something like `mpirun -np 1 ./tiegcm` in `advance_model.csh` by setting `set parallel_model = "false"`. Although this is what I'm attempting to do, this simply calls `mpirun.lsf ./filter`. I have already attempted to approximate this in `run_filter.csh` by simply using `mpirun ./filter` (LSF not being available on my system).

**Comment by benmenadue** [comment]
```mbind: Invalid argument```

This is relatively benign. You get that when you try to initialise the Infiniband device but aren't allowed to allocate memory on the NUMA node that the IB card is attached to.

It's an artefact of only requesting a single CPU -- your job will be running in a cgroup that is restricted to just the 1 CPU along with the NUMA node that it is associated with; if that's not the NUMA node that the IB card is attached to, you'll get this message. But since a single-core job won't be using the IB network anyway, it shouldn't affect anything.

As for trying to launch MPI "sub-programs" from each MPI rank of a larger, main program, I've replied to your e-mail to our helpdesk. I've never tried running something like that before, and I'm not sure if it would work. MPI isn't really designed for that, and I can see many places that it could go wrong. (That's not to say that it's not possible, I've just never seen it done before.)

**Comment by timhoar** [comment]
I am getting a clearer picture (I think).  Let's be clear - `mpirun -np 1 ./filter` launches _filter_ just fine.
It runs, it determines it needs to advance the model, so it issues the system command to run _advance_model.csh_ and all the serial executables in _advance_model.csh_ run successfully. The problem occurs when trying to run another MPI program - while filter is still technically running.

`run_filter_async4.csh`  is designed to enable: 

1. running an MPI filter and either MPI models (in which case each instance of the model uses the same tasks as filter and the ensemble is advanced one after another - **async 4**) or
2. an MPI filter and serial models (in which case each model instance uses a single task - **async 2**). 

Since you state early on that tiegcm must be compiled with MPI, you should be running **async 4** - even if you are running with a single task.  You have a parallel model, so you should have `parallel_model = .true.` and the form of the `mpirun` command has to match your system - I suspect, including the processor/task resource.  Since _filter_ and each instance of _tiegcm_ share the same tasks, you must run _filter_ with at least as many tasks as are needed by _tiegcm_.

The fact that _tiegcm_ is not starting is probably related to the fact that the tasks are still occupied by _filter_.  `run_filter_async4.csh` runs _filter_ in  the background `(setenv HOME $filterhome; mpirun.lsf ./filter) &` and then uses shell named pipes to determine what program (filter, tiegcm, wakeup_filter) should be running on the tasks.  Clearly - you have to change `mpirun.lsf` to whatever syntax is appropriate for your system.

Let me know how that goes.

**Comment by benmenadue** [comment]
Yes, that would work, although on our system it's a little more flexible in that you don't need to use the same number of processes for filter and TIE-GCM. The placement and binding of processes is handled by the MPI runtime, independent of any other things running in the PBS job, so something like `mpirun -np 2 ./a & mpirun -np 1 ./b` would result in running an `a` and a `b` on the first slot allocated to the job and just an `a` on the second slot.

Of course, you'll need to make sure that the `filter` tasks are actually asleep when they expect TIE-GCM to be running. In the `async=4` mode, how does `filter` wait for the model tasks to run? While a process will be sleeping if waiting on a pipe, if you're waiting on e.g. `MPI_Barrier` you'll actually be spinning and so stealing approximately half of the cputime from the corresponding TIE-GCM process that is be running on that core.

**Comment by timhoar** [comment]
I will have to ask if filter is sitting on an MPI_Barrier for that time ...
Let me get back to you.


Tim Hoar
Data Assimilation Research Section
National Center for Atmospheric Research
thoar@ucar.edu
303.497.1708

**Comment by benmenadue** [comment]
I just had a look through the code and it looks pretty sensible -- it appears that each MPI process blocks on its own named pipe and is woken back up by another MPI program - `wakeup_filter` - that writes to those pipe. So it shouldn't spin while waiting for the model to progress.

**Comment by gwbowden** [comment]
Thanks very much for your help Tim and Ben. Using the `async = 4` option the script `run_filter_async4.csh` (as suggested) ran all copies of TIE-GCM successfully. Moreover, compiling the `filter` program with the `-nompi` option allowed the original `run_filter.csh` scrip to be run with `async = 2`, though obviously with only 1 filter process calling each of the model runs in series.

In the past has TIE-GCM been run more often with `async = 4` or `async = 2` and is there much difference in performance? Has the "async 5" option mentioned in https://www.image.ucar.edu/DAReS/DART/Manhattan/docs/html/mpi_intro.html been used?

**Comment by timhoar** [comment]
Great news that you are running!

I believe TIE-GCM has (almost always) been run in async 4.  Conceptually, it is trivial to run filter with an observation sequence file that only has observations for the current assimilation cycle - in which case DART does not need to advance the model at all. The scripting for such a case would have to be written, and the obs_sequence_tool would need to parse the observations into assimilation-sized files.
There are tradeoffs to consider.  DART creates diagnostic files and writes the model metadata into the file. Each new execution of filter would create new diagnostic files and repeats the metadata. The directories get increasingly full of output files and navigating them gets unwieldy - we have had some experiments where an 'ls' in the directory takes longer than the model advance or assimilation! This has implications for the scripting implementation.
On the plus side, you can fire off the model advances with a job array strategy and submit the job to filter as a dependent job. The model advances are very short, so the jobs 'backfill' well. The turnaround can be better than waiting for a large, long job. You get to tailer the resources for each job (filter, tie-gcm) independently.
As an aside ... there is no real 'async 5' ... if the model does not need to advance, any 'async' value will do. It's all in the scripting.
