### ISSUE TITLE
Updating cam-fv perfect_model scripts

### ISSUE THREAD

**Issue by kdraeder** [NCAR/DART#210]
If this turns out to be a complicated issue, I'll write a full spec for it.

The shell_scripts/*setup_pmo and perfect_model.csh (which runs perfect_model_obs)
have been completely neglected since CESM 1.2.1, so they need to be updated to work with CESM 2.1.  
Am I right in remembering that setup_pmo should parallel setup_hybrid
and perfect_model.csh(.template) should parallel assimilate.csh(.template)
to make it easier to maintain them?
Setup_hybrid and assimilate.csh.template are up to date and were used in the CAM6 Reanalysis.

**Comment by kdraeder** [comment]
@timhoar This should only take a minute to answer.  Thanks!

**Comment by timhoar** [comment]
Right.  My thinking is that if someone has invested time to learn setup_pmo, it would be easier to understand setup_hybrid. By making them REALLY similar, people could also 'diff' them to help understand what is meaningfully different between the two.
Ditto for perfect_model.csh and assimilate.csh

The hard part for me is that 'perfection is the enemy of progress' ... it's easy to get carried away .

**Comment by kdraeder** [comment]
I'm motivated towards the progress end of the spectrum by a current project, 
so I'll leave perfection for another day. Thanks.

**Comment by kdraeder** [comment]
It turned out to have more of a footprint than I expected,
so I'm closing this issue and opening a new one, in order to use the spec template.
