### ISSUE TITLE
Feature request: reorganize the obs_converters/utilities dir

### ISSUE THREAD

**Issue by nancycollins** [NCAR/DART#221]
### Use case  
Reorganize the obs_converters/utilities dir

### Is your feature request related to a problem?  
not a problem, but trying to collect code in a logical location

### Describe the your preferred solution  
my suggestions for files in this directory:
- the observations/obs_converters/utilities dir should only contain 1 file - the routines that help add obs to a sequence plus higher level netcdf routines that help read in arrays and fix missing values, which is a common task for obs files distributed in netcdf.
- it should use the netcdf utility routines which weren't written when it was started.
- make_fake_obs should move to a separate dir under obs_converters/test_obs and be renamed make_test_obs (or make_test_obs1, make_test_obs2, ...)
- the oned and threed_sphere dirs should be removed from the observations/obs_converters/utilities directory.  programs should be built in observations/utilities instead.
- obs_seq_utilities_mod should move to the assimilation_code/modules/observations dir
- obs_seq_utilities_mod should have a single copy of all the obs routines that are currently replicated (see issue #185)
- any routines in the obs_sequence_mod that don't need access to the private parts of the obs_seq derived type or private routines should move into the utils module
- print_obs_seq should take a verbosity flag and print minimal info, medium amounts of info, or really really verbose info.

### Describe any alternatives you have considered  
closing my eyes and singing 'la la la' ?

edit: clarify which utilities dir i'm talking about - there is one at the observation/utilities level and one at the observation/obs_converters/utilities level.  the first one contains executable programs.  the second one was intended to only contain modules helpful specifically for converters.

**Comment by hkershaw-brown** [comment]
this is out of date since v10.0.0
