### ISSUE TITLE
Feature request: obs_info.f90 should use print_obs_seq_summary

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#222]
### Use case  
Any time anyone wants to explore the contents of an observation sequence file to report on the number and kinds of observations in the file. 

### Is your feature request related to a problem?  
This is simply a code cleanup ... print_obs_seq_summary() already does this, no need to have repeated code.

### Describe the your prefered solution  
Use the existing obs_sequence_mod.f90:print_obs_seq_summary() instead of the nearly identical code in obs_info.f90
Care must be taken to still provide the abilty to write out the comma-separated-values list that is useful to read into Matlab, or Excel or ... 

### Describe any alternatives you have considered  
None - just 'thinking out loud'

**Comment by nancycollins** [comment]
this is part of / related to issue #221.
