### ISSUE TITLE
Feature request: support CLM on public branch

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#224]
### Use case  
Even through v9.10.z, the CLM support on the public repository is limited to versions up to 8.y.z
The CLM support for versions 9.y.z are on a private repository and can now be made fully public.

### Is your feature request related to a problem?
There are some potential complications pertaining to the handling of the Time dimension as many use-case scenarios for CLM use history file variables (which have multiple timesteps) as part of the DART state. Additional complications may occur as different ensemble members of CLM may have different numbers of snow layers, which means we have to fully support the use of missing values in the state to keep the size and shape of the DART state vectors consistent across all members. To my knowledge, this has not been fully tested with the refactoring that occurred with v9.y.z

Furthermore, the partitioning function that takes snow water equivalent (SWE) and updates the prognostic variables (which have layers) consistent with the update to SWE have not been fully supported or tested with recent versions of CLM. Depending on the invasiveness, this may be a separate issue.

### Describe the your prefered solution  
Create a feature branch from the most current private branch, merge the public main branch onto the feature branch and develop, test, repeat. Compare the results to a known solution that we believe to be correct (from the private repo). That will be using CLM release-clm5.0.06 (circa August 2018) .  Supporting the newest CLM (release-clm5.0.34) is a subsequent issue.

### Describe any alternatives you have considered
N/A

**Comment by hkershaw-brown** [comment]
fixed in #313
