### ISSUE TITLE
need better tests for parse_args_mod

### ISSUE THREAD

**Issue by nancycollins** [NCAR/DART#231]
the developer_tests/utilities directory has a parse_args_test.f90 file, and the work directory has a parse_args_test.in input file.  however, the test program never runs the second part of the test (testing name=value pairs) because control-d ends not only the first part of the test but the second part as well.

recommend there be a reserved keyword (e.g. quit) to end each section.

the test input file has only a few simple lines and does not test escape characters.  it does test double quoted strings with embedded white space but not single quotes.  it also has no tests for name=value pairs.  it does not test very long lines or blank lines, or mismatched quotes (e.g. only an opening quote).

**Comment by hkershaw-brown** [comment]
see issue #219 for some discussion.

**Comment by hkershaw-brown** [comment]
closing inactivity
