### ISSUE TITLE
perfect_model_obs could/should honor the clamping values for variables

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#242]
### Use case  
I am running perfect_model_obs under the CLM framework and there are many directly-observed (i.e. COMMON_CODE) observations pertain to variables that have clamping values. Lets say the quantity is bounded below by 0.0
pmo can add noise to the truth and come up with a negative value. I'd like to have these synthetic observations be within the bounds of the variable responsible.

### Is your feature request related to a problem?  
I cannot assimilate some of the negative observations and update the CLM state such that the model can make a forecast.

### Describe the your prefered solution  
Since perfect model obs uses the state_structure (which has the clamping info for each variable) ... it may be possible to query
that and use it to prevent observations outside the limits. Naturally, I am not talking about 'compound' FOs (a term I just made up to indicate that multiple parts of the state must be combined in some fashion)

### Describe any alternatives you have considered  
I have modified PMO by hand to resample N times till the value is above 0.0 ... for CLM, everything we

**Comment by nancycollins** [comment]
the limits on values of synthetic obs from PMO are not always the same as the assimilation state structure limits, so i wouldn't want to reuse those values for a new purpose.  for example, wrf has some fields that can't be 0 for the model advance so the clamping limit is a small positive value, but a PMO generated obs value can go to 0 without problems.  and as you point out, more complex forward operators will not be affected by this which is not consistent.

ideas: 

1. if you leave PMO as-is, when model_interpolate() is called from filter during an assimilation run it should reject obs that are out of range.  an error in an instrument might generate the same problems.  it should be fine if you don't assimilate some obs generated by PMO. 

2. we could make a way to specify non-gaussian error values to be added to the original obs interpolation value.  this seems  like it might be more appropriate for obs sampled from bounded values.

3. if important enough, we could add separate PMO obs clamping values.  that would cover all synthetic obs, not just the ones that are generated by direct interpolation and could have different limits if necessary. but this has the same drawbacks as we already create by clamping state values.  moha and jeff are looking at ways to avoid clamping so maybe some of those techniques could apply here as well.

**Comment by hkershaw-brown** [comment]
leaving this as wont fix for now.
