### ISSUE TITLE
pgi does not like the inflation flavors being integers.

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#245]
pgi does not like the inflation flavors being integers. 

```
 ERROR FROM:
  source : utilities_mod.f90
  routine: check_namelist_read
  message:  INVALID NAMELIST ENTRY:    inf_flavor                  = 2,                       0, in namelist filter_nml
```

```diff
- inf_flavor                  = 2,                       0,
+ inf_flavor                 = '2',                     '0',
```

_Originally posted by @hkershaw-brown in https://github.com/NCAR/DART/issues/219#issuecomment-849177858_

**Comment by hkershaw-brown** [comment]
Q. Is this non-standard fortran?

**Comment by nancycollins** [comment]
in the distant past the fortran standard didn't specify anything about namelists so there was a lot of differences in what different compilers supported.  it is a part of the language in the sense you can say:  read(6, nml=bob) and it will expect to read variables contained between & and / that are part of namelist /bob/.  but detailed rules about namelist syntax are still a bit vague.

i'm reading the (very small) section about namelists in my fortran 2018 book and it says the variable values have to be the same type as the variable is declared.  so pgi might actually be more correct in requiring quotes around character values compared to other compilers if inf_flavor is declared as a character variable.

it also says the compilers should support comments at the end of each line preceeded with !, like:

&bob
 variable1 = 1.0    ! this is a comment
 variable2 = 2.0   ! this is also a comment
/

but i wouldn't chance it until around 2030...

**Comment by nancycollins** [comment]
i think inflation should go back to using integers for inf_flavor.  internally it can map the integers to strings and then the code can use the strings, or whatever is the smallest footprint change.

at some point i think the better solution is to move all inflation related items to their own namelist, at which time we can change the name of the item and change the type to character.  (e.g. &inflation_nml::inflation_type = 'Adaptive' or whatever).  there are better names for a lot of the other inflation namelist items (where better == easier for users to understand).

i think this is broken as-is.  i think i read that PGI is going to be one of the compilers available on the new machine?  in any case it's a fortran compiler that our users have access to so we should make sure it's supported.
