### ISSUE TITLE
bug: cam-fv quad_vals 

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#246]
:bug: Your bug may already be reported!
Please search on the [issue tracker](https://github.com/NCAR/DART/issues) before creating a new issue.

### Describe the bug

Steps someone needs to take to reproduce the bug:
  Run cam-fv. Have an ensemble size > 4.   Use debugging flags if you want to stop on the error. 

quad_vals is declared`quad_vals(ens_size,4)`
but is passed to `call quad_lon_lat_evaluate(interp_handle, lon_fract, lat_fract, &
                              quad_vals(:,imem), interp_vals(imem), status_array(imem))`

### Error Message  
![Screen Shot 2021-06-23 at 9 01 35 AM](https://user-images.githubusercontent.com/20047007/123131195-b23c7480-d40a-11eb-9fcd-1c636520b629.png)

### Which model(s) are you working with?
cam-fv 

### Screenshots   
Without debugging flags, filter runs to completion, but you get this:
![Screen Shot 2021-06-23 at 10 07 20 AM](https://user-images.githubusercontent.com/20047007/123131305-d0a27000-d40a-11eb-8d66-32f3ea9f9aab.png)

Note, 3 member ensemble was not showing obvious problems (or erroring out) because ens_size < 4.

### Version of DART      
I believe all versions after this commit f8f8e12c037944cf492962127fc1b61ad8893e1f on March 10th 2020. 

### Have you modified the DART code?   
Nope

### Build information
Problem detected by Gio on Zeus, but it is a problem on all platforms.

**Comment by kdraeder** [comment]
Hi Helen,
thanks for wrapping up the quad_vals issue,
except that it's showing that I still don't understand git(hub)
(or something's broken).  I see the fix in the main branch,
but that doesn't seem to have been propagated to the Manhattan branch.
Is that expected?
Kevin

**Comment by hkershaw-brown** [comment]
I'll put in on the Manhattan branch now.  Thanks!

**Comment by kdraeder** [comment]
Thanks, but if fixes on one branch need to be propagated
to every other branch by hand, that's at best a major pain
and at worst a recipe for users being deluded into thinking
that they're using fixed code.

**Comment by hkershaw-brown** [comment]
yup, thats why I'm going for having a main branch with tagged releases.
