### ISSUE TITLE
bug: Constants in the model_mod for MPAS

### ISSUE THREAD

**Issue by criedel40** [NCAR/DART#251]
I noticed that an atmospheric constant (specifically Cp or Specific heat of dry air at constant pressure) in model_mod.f90 in the mpas_atm directory does not match the value found in the MPAS source code.

DART Cp Constant Value (line 215 in model_mod.f90): 1003.0
MPAS Cp Constant Value (MPAS-Release/src/framework/mpas_constants.F: line 33): 1004.5

I believe you would want these constant to match up when converting potential temperature to temperature in the forward operator function (theta_to_tk line 7428).

**Comment by hkershaw-brown** [comment]
looks like MPAS changed this in 2016:
https://github.com/MPAS-Dev/MPAS-Model/commit/d2b19b6237e98f33d20e62428dcdf044b5106f2a
so between versions 4.0 and 5.0
