### ISSUE TITLE
developer_test/io/work/input.nml  

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#255]
### Describe the bug

duplicating quantity from land_quantities_mod

The developer_test/io/work/input.nml is not using the quantities_mod construct and so requires that the default_quantities_mod.f90 has all the quantities. So - if you add a quantity to a specific file, you also have to add it to the default_quantities_mod.f90.

**Comment by hkershaw-brown** [comment]
not sure this is a bug.  If it ships with dart, it should probably be in the default_quantities_mod.f90
