### ISSUE TITLE
mpich mpif08

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#261]
I think the mpi_utilities errors are mpich using f77 bindings when you `use mpi`. Hello world mpi (no dart code) will not compile if you have a mpi_send(integer) mpi_send(real) in the same file.

[hello.f90.txt](https://github.com/NCAR/DART/files/6525415/hello.f90.txt)
[hello_f08.f90.txt](https://github.com/NCAR/DART/files/6525419/hello_f08.f90.txt)

The f08 mpi module `use mpi_f08` follows the fortran standard. 
There is a branch mpi_f08 which has a version of mpi_utilites_mod.f90 with mpi_f08 bindings. This will work with mpich and gfortran 10+ (only done a quick test).
The cray window module (cray pointers) could get replaced with iso_c_bindings. 

or short term solution: `port select --set mpi openmpi-mp-fortran`

_Originally posted by @hkershaw-brown in https://github.com/NCAR/DART/issues/158#issuecomment-846307106_

**Comment by hkershaw-brown** [comment]
I love these foundation shaking questions from Nancy.   Have you played with autoconf to configure/make DART vs. mkmf?

**Comment by hkershaw-brown** [comment]
other notes from #288
review MPI_INTEGER_KIND, COUNT MPI3 as part of this update.

**Comment by hkershaw-brown** [comment]
up-to-date now.  I think this should go in a f2008(3) update (see https://github.com/NCAR/DART/pull/288).  Hanging out on the mpi_f08 branch now

**Comment by hkershaw-brown** [comment]
moved mpi_f08 https://github.com/hkershaw-brown/DART/tree/mpi_f08 
someone can grab it or not as needed if they are updating to f08.

**Comment by hkershaw-brown** [comment]
Gust gfortran

hkershaw@gust01:~/DART/models/lorenz_96/work.gfortran> module -t list
ncarenv/23.04
craype/2.7.20
gcc/12.2.0
ncarcompilers/0.8.0
hdf5/1.12.2
netcdf/4.9.1
cray-mpich/8.1.25

<img width="1270" alt="Screen Shot 2023-05-01 at 6 16 12 PM" src="https://user-images.githubusercontent.com/20047007/235541023-212ad613-7b3a-4ffc-8457-a55447b078a6.png">

**Comment by hkershaw-brown** [comment]
To reproduce this on gust you can use the following modules:

```
hkershaw@gust01:~/DART/models/lorenz_96/work> module load gcc
hkershaw@gust01:~/DART/models/lorenz_96/work> module -t list
ncarenv/23.04
craype/2.7.20
gcc/12.2.0
ncarcompilers/0.8.0
hdf5/1.12.2
netcdf/4.9.1
cray-mpich/8.1.25
```

`./quickbuild.sh` gets you:

```
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
/glade/u/home/hkershaw/DART/assimilation_code/modules/utilities/mpi_utilities_mod.f90:649:18:

  595 |       call MPI_Ssend(srcarray, int(itemcount,i4), datasize, dest_id, tag, &
      |                     2
......
  649 |    call MPI_Ssend(itime, 2, MPI_INTEGER, dest_id, tag*2, my_local_comm, errcode)
      |                  1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(8)).
```

**Comment by mjs2369** [comment]
Updated the old mpi_f08 branch to main. Updated branch located at [](https://github.com/NCAR/DART/tree/mpif08)
