### ISSUE TITLE
suggest making a single update to remove remaining svn lines and fix our download location

### ISSUE THREAD

**Issue by nancycollins** [NCAR/DART#271]
### Use case  
we need to eventually remove all the svn lines, and we need to update our copyright section to fix the URL. 

### Is your feature request related to a problem?  
it seems like we can either update each file one by one as we go, or we could dedicate a single pull request to updating them all, with absolutely no other code or doc changes mixed in.

### Describe your preferred solution  
i guess i'd rather not mix code changes and cosmetic changes.  updating all the files at once seems disruptive but less so if it's a single update?

### Describe any alternatives you have considered  
we could just ignore this altogether!  :)

**Comment by hkershaw-brown** [comment]
what do you want to change the copyright url to?
http://www.image.ucar.edu/DAReS/DART/DART_download 
does take you to the copyright.

Hot take, I think DART missed its chance to remove svn info when the repo was moved to git.

**Comment by nancycollins** [comment]
ah, maybe i'm behind the times.  i thought www.image.ucar.edu was going awa?

**Comment by hkershaw-brown** [comment]
we'll burn that bridge when we get to it

**Comment by hkershaw-brown** [comment]
The svn lines and licensing came up at the stand up a few months ago. 

The repo files are a mixture of files that have the lines, files that don't.  For new files, we're not adding the svn lines.
