### ISSUE TITLE
integrate_model_parallel.f90 vs integrate_model.f90

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#274]
integrate_model_parallel.f90

does not appear in any pathnames files. There is integrate_model.f90. Both files contain the same mpi calls.

I think integrate_model_parallel.f90 is newer code, but the path_names_files were not updated.

Pick one and move on.

**Comment by nancycollins** [comment]
integrate_model_parallel.f90 looks like the older, original code renamed for some reason -- it uses aread_state_restart and awrite_state_restart which are the old i/o routines.  integrate_model.f90 calls read_state and write_state which are current.  i'd say remove integrate_model_parallel.f90 -- it is in the repo if someone needs to refer to it sometime in the future.

**Comment by hkershaw-brown** [comment]
you are on holiday

**Comment by hkershaw-brown** [comment]
removing  integrate_model_parallel.f90  it is.

**Comment by nancycollins** [comment]
well, i am retired so technically i'm always on vacation!  but i'm back from our trip and catching up on the email that i did not read while in seattle!!  :)
