### ISSUE TITLE
bug: model size is sometimes i8 sometimes i4

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#278]
:bug: Your bug may already be reported!
Please search on the [issue tracker](https://github.com/NCAR/DART/issues) before creating a new issue.

Originally reported by a user trying to run a very wrf large model. 

### Describe the bug

1. List the steps someone needs to take to reproduce the bug.  
use wrf model mod with model size declared as i8
run perfect model_obs

2. What was the expected outcome?
I think a user should be able to have a model size i8

3. What actually happened?  
bomb in direct_netcdf_mod.f90.  For example `subroutine read_transpose`
`169 integer,                   intent(inout) :: dart_index `

There may be other locations where integer is being used instead of integer(i8)

### Which model(s) are you working with?
WRF

### Version of DART      
v9.11.8

### Have you modified the DART code?   
Yes  to add i8 to wrf model_mod.f90

**Comment by hkershaw-brown** [comment]
big pop run with i8?

**Comment by nancycollins** [comment]
testing with 1/10th degree pop should smoke out any i8/i4 issues introduced into the main dart code.  but if the WRF model_mod code has i8/i4 issues with the state vector size or indices into the state vector, you'll have to find/construct a large wrf state to test that.

**Comment by hkershaw-brown** [comment]
do you know where 1/10th degree pop is? Is this it: https://github.com/NCAR/DART_development/tree/static_data

**Comment by nancycollins** [comment]
the code?  it's just the standard models/POP 

the data?  good question.  possibly on image.ucar.edu in the data area, or on campaign storage, or lost to the sands of time.

**Comment by hkershaw-brown** [comment]
The big pop test case as is, is too small to catch  `direct_netcdf_mod.f90` i4 vs i8

big pop test case:
`/glade/p/cisl/dares/DART_test_cases/pop/pop_tx0.1v2/`

|                  | # elements       |
|-----------|----------------|
| model size | 2,151,360,000 |
| 3D variable size | 535,680,000 |
| 2D variable size | 8,640,000 |
| i4 | 2,147,483,647 |

````
 PE 0: verify_state_variables variable  1 is SALT_CUR, QTY_SALINITY, UPDATE
 PE 0: verify_state_variables variable  2 is TEMP_CUR, QTY_POTENTIAL_TEMPERATURE
 , UPDATE
 PE 0: verify_state_variables variable  3 is UVEL_CUR, QTY_U_CURRENT_COMPONENT, 
 UPDATE
 PE 0: verify_state_variables variable  4 is VVEL_CUR, QTY_V_CURRENT_COMPONENT, 
 UPDATE
 PE 0: verify_state_variables variable  5 is PSURF_CUR, QTY_SEA_SURFACE_PRESSURE
````

4 3D variables = 2,142,720,000 so you have 4,763,647 spare before you hit i4 vs i8 problems keeping track of the dart index in the read/write calls.

same deal with `state_structure_mod.f90` offset calculation:

```
1394 integer :: ndims, offset
1401 offset = get_index_start(dom_id, var_id)
```
So the i4 i8 for netcdf and state_structure might have been in the code forever since no one has run anything big enough to hit problems.

-> Add more variables to big-pop or try mega-WRF.

**Comment by hkershaw-brown** [comment]
note  on wrf 
https://github.com/NCAR/DART/commit/9609475699f84e15f446d67ebee6f793695f9e65

**Comment by hkershaw-brown** [comment]
model_mod.f90 docs (template and default) have the convert_vertical_obs arguments (loc_types(:))  in convert_vertical_state instead of the convert_vertical_state arguements (loc_indx(:))
https://docs.dart.ucar.edu/en/latest/models/utilities/default_model_mod.html?highlight=convert_vertical
https://docs.dart.ucar.edu/en/latest/models/template/readme.html?highlight=convert_vertical

**Comment by hkershaw-brown** [comment]
How does the itemcount check work in mpi_utitlies when you have a srcarray bigger than 2^31-1?

```
subroutine send_to(dest_id, srcarray, time, label)
integer :: itemcount
itemcount = size(srcarray)
```

https://github.com/NCAR/DART/blob/62ecfa2a2b4c7de55f98f434de49e076060fd82c/assimilation_code/modules/utilities/mpi_utilities_mod.f90#L155

https://github.com/NCAR/DART/blob/62ecfa2a2b4c7de55f98f434de49e076060fd82c/assimilation_code/modules/utilities/mpi_utilities_mod.f90#L574

**Comment by hkershaw-brown** [comment]
ifort not so good:

```
hkershaw@cisl-fisher test-mpi $ cat big_itemcount.f90 
program itemcount_test

integer, parameter :: i8 = SELECTED_INT_KIND(13)
integer, parameter :: SNDRCV_MAXSIZE = 2 * 1000 * 1000 * 1000 
integer(i8), parameter :: length = 3120000000_i8

double precision :: srcarray(length)
integer :: itemcount

srcarray(:) = 5.d0

itemcount = size(srcarray)
print*, 'itemcount, size(srcarray)', itemcount, size(srcarray)

print*, '(itemcount <= SNDRCV_MAXSIZE)', (itemcount <= SNDRCV_MAXSIZE)
print*, srcarray(3120000000_i8)

end program itemcount_test
hkershaw@cisl-fisher test-mpi $ ifort -warn big_itemcount.f90 
hkershaw@cisl-fisher test-mpi $ ./a.out 
 itemcount, size(srcarray) -1174967296 -1174967296
 (itemcount <= SNDRCV_MAXSIZE) T
   5.00000000000000     
hkershaw@cisl-fisher test-mpi $ 
```

**Comment by hkershaw-brown** [comment]
noticed this when testing:

direct_netcdf_mod.f90 creates netcdf files in 64bit offset mode:
https://github.com/NCAR/DART/blob/62ecfa2a2b4c7de55f98f434de49e076060fd82c/assimilation_code/modules/io/direct_netcdf_mod.f90#L1617

netcdf_utilities_mod.f90 creates netcdf files in classic mode 
https://github.com/NCAR/DART/blob/62ecfa2a2b4c7de55f98f434de49e076060fd82c/assimilation_code/modules/utilities/netcdf_utilities_mod.f90#L2409

Do we care about this? I don't know. Just making a note. May move to a separate issue.
