### ISSUE TITLE
bug: NAG compiler with null_mpi_utilities

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#281]
:bug: Your bug may already be reported!
Please search on the [issue tracker](https://github.com/NCAR/DART/issues) before creating a new issue.

### Describe the bug

1. List the steps someone needs to take to reproduce the bug.  
`quickbuild.csh` for lorenz_96

2. What was the expected outcome?
successful build without mpi
3. What actually happened?  
The following error:
```
[NAG Fortran Compiler normal termination, 9 warnings]
nagfor -O -mismatch -I/usr/local/netcdf-c-4.6.1-f-4.4.4-gcc-g++-8.1.0-nag-6.2/include  -c	../../../assimilation_code/modules/utilities/null_mpi_utilities_mod.f90
NAG Fortran Compiler Release 7.0(Yurakucho) Build 7005
Error: ../../../assimilation_code/modules/utilities/null_mpi_utilities_mod.f90, line 32: Invalid #line directive
Error: ../../../assimilation_code/modules/utilities/null_mpi_utilities_mod.f90, line 47: Invalid #line directive
Error: ../../../assimilation_code/modules/utilities/null_mpi_utilities_mod.f90, line 47: Syntax error
Warning: ../../../assimilation_code/modules/utilities/null_mpi_utilities_mod.f90, line 656: SET_TIME explicitly imported into MPI_UTILITIES_MOD but not used
[NAG Fortran Compiler pass 1 error termination, 3 errors, 1 warning]
Makefile:16: recipe for target 'null_mpi_utilities_mod.o' failed
make: *** [null_mpi_utilities_mod.o] Error 2
```

fixsystem?

### Which model(s) are you working with?
lorenz_96, POP

### Version of DART      
Which version of DART are you using? 
v9.11.9

### Have you modified the DART code?   
No  

### Build information
Please describe:  
 1. hobart 
 2. NAG Fortran Compiler Release 7.0(Yurakucho) Build 7005

**Comment by nancycollins** [comment]
the nag block in both null_mpi_utilities_mod.f90 and mpi_utilities_mod.f90 have bad formatting.

i will make a branch and issue a pull request to fix these two files so they'll compile for both nag and other compilers.
