### ISSUE TITLE
bug: convert_airs_L2 giving error using MERRA data  

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#293]
:bug: Your bug may already be reported!
Please search on the [issue tracker](https://github.com/NCAR/DART/issues) before creating a new issue.

### Describe the bug

Use `convert_airs_L2` on MERRA data. https://disc.gsfc.nasa.gov/datasets?keywords=AIRX2RET&page=1

Reported by a user

### Error Message  
```
Error           -1  reading field 
```

### Which model(s) are you working with?
CESM

### Version of DART      
Which version of DART are you using? 
unknown

### Have you modified the DART code?   
unknown

### Build information
Please describe:  
unknown, maybe all builds.

**Comment by kdraeder** [comment]
Is the user Yonghan Choi andor YoungChae Kwon?

**Comment by nancycollins** [comment]
it's yonghan choi.  tim got this report in a note which he forwarded to dart.

**Comment by kdraeder** [comment]
Tim reported that
Apparently, NASA has reprocessed the MERRA data and altered the content of the level 2 HDF files just enough to break the DART converter.
https://disc.gsfc.nasa.gov/datasets?keywords=AIRX2RET&page=1
which has links to the data set we've been using (version 006) and the new one:
Aqua/AIRS L2 Standard Physical Retrieval (AIRS+AMSU) **V7.0** (AIRX2RET 7.0)

The files he sent to me (and probably Tim) are not very useful.
I'll respond to him directly and find out whether he's converting the 006 or v7.0

**Comment by kdraeder** [comment]
He's converting the version 006 files, so that doesn't explain it.

**Comment by hkershaw-brown** [comment]
Kevin where you able to reproduce the problem with the converter and confirm (or not) that this is a bug in our converter?

**Comment by kdraeder** [comment]
I have not tried to do that.
It seemed like a better use of my time to get Gio's code working and then send it to Yonghan,
instead of working on both related problems at the same time.  That has clearly not been satisfactory
for Yonghan or me.

**Comment by hkershaw-brown** [comment]
closing as unconfirmed for now.
