### ISSUE TITLE
bug: mismatch somewhere between 31 and 32 chars for obs types and/or quantities

### ISSUE THREAD

**Issue by nancycollins** [NCAR/DART#344]
:bug: some variable is 32 chars but should be declared obstypelength which is 31

### Describe the bug

arthur has a collaborator who got errors from the obs_impact_tool.  it failed with the error msg below.  it is possible the root cause is comparing a 32 char version of 'UNKNOWN________0' with 'UNKNOWN'.  that's 7 chars of UNKNOWN, 24 blanks, and then a null char which was presumably not updated to be a blank because it was assigned a 31 char string.   (this is just a guess at this point.)
 
error msg:
 ERROR FROM:
  add_toc:
  routine: add_toc:
  message: word already in toc: UNKNOWN                      
  message: ... cannot have duplicate entries

this is with an older version of preprocess, not the current one.  there is a comment in the DEFAULT_obs_kind_mod.F90 that mentions 32, not 31, length - that should be fixed, too.

on our other platforms the code works fine.  i can't see why this particular compiler/machine failed.  it was with ifort 19.0.4.243 Build 20190416 and the user was compiling -O3 if that matters.
 
we limit the names of quantities and observation types to 31 chars because we make fortran parameters out of the names. compilers before 2003 limited names to 31 (not 32!) chars.  more recent compilers allow longer strings (63 i believe)

see attached file for places where the variable name looks like we're putting quantity/type info into it and it's explicitly declared as 32, not 'obstypelength'.  i don't know if any of these could have triggered this user's error, but it is inconsistent.

character(len=32) :: impact_only_same_kind = ' ' ./models/LMDZ/model_mod.f90

character(len=32) :: ob_type ./models/coamps_nest/navdas_innov_mod.f90

character(len=32) :: kind_name ./models/coamps/coamps_restart_mod.f90

character(len=32) :: kind_name ./models/mpas_ocn/model_mod_check.f90
character(len=32) :: quantity_name ./models/cam-fv/chem_tables_mod.f90

character(len=32) :: fields_to_perturb(MAX_PERT)     = ""
character(len=32) :: ucasename ./models/cam-fv/model_mod.f90

character(len=32) :: obs_kind_name ./models/MITgcm_ocean/dart_MITocean_mod.f90

character(len=32) :: this_obs_name ./assimilation_code/programs/obs_utils/obs_assim_count.f90
character(len=32) :: this_obs_name ./assimilation_code/programs/obs_assim_count/obs_assim_count.f90

character(len=32) :: state_size_string, obs_key_string, identity_obs_string ./assimilation_code/modules/observations/forward_operator_mod.f90

character(len=32) :: string(2)
character(len=32) :: kindString
character(len=32) :: kind_string
character(len=32) :: kind_string ./developer_tests/io/test_state_structure.f90

character(len=32) :: kindstr ./developer_tests/io/test_read_write_restarts.f90

character(len=32) :: observation_name = 'GPS_TOTAL_PRECIPITABLE_WATER' ./observations/obs_converters/tpw/convert_gpspw.f90
character(len=32) :: observation_name = 'MODIS_TOTAL_PRECIPITABLE_WATER' ./observations/obs_converters/tpw/convert_tpw.f90

character(len=32) :: obs_name, obs_no_support(max_defined_types_of_obs) ./observations/obs_converters/var/littler_tf_dart.f90

character(len=32) :: sig_wind_type = 'unknown' ./observations/obs_converters/MADIS/convert_madis_rawin.f90

character(len=32) :: solution ./observations/obs_converters/quikscat/quikscat_JPL_mod.f90

**Comment by hkershaw-brown** [comment]
Looks like we could improve the documentation on the 31,32 length
DEFAULT_obs_kind has this comment:

https://github.com/NCAR/DART/blob/2d3f1534fd4956d839a637d1eeb7b5570c603e50/assimilation_code/modules/observations/DEFAULT_obs_kind_mod.F90#L113

This is a side note on what is in types_mod.  I'm a bit worried about shoving a bunch of parameters in types_mod. 

MAX_NUMBER of domains is state structure. It should inside the state_structure module surely?

Also, types_mod is types (real(KIND=X), logical, integer) rather than observation type and dart quantity (kind). I think since DART terminology of kind, type for quantity, observation is easy to mix up anyway, the concepts (precision vs. DART) should be separated in different modules.

**Comment by nancycollins** [comment]
i agree that the types_mod should be limited to compiler-specific related types, and other parameters should go someplace else.  types currently has things like:  `public :: t_kelvin, es_alpha, es_beta, es_gamma, gas_constant_v, gas_constant`  which are model dependent, surely.

**Comment by hkershaw-brown** [comment]
Hey Nancy do you have a reproducer for this bug?  

Possible first bug fix for Marlee.

**Comment by nancycollins** [comment]
no, sorry.  the only place we've run into it is on the system of a user in mexico.  i could never make it happen for me anyplace i tried it.

**Comment by hkershaw-brown** [comment]
unable to reproduce this bug
