### ISSUE TITLE
argument mismatch wrf pert_model_sounding

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#351]
> just a warning that with the new build system, i found that models/wrf/experiments/Radar/IC/sounding_perturbation/pert_sounding_module.f90 does not compile with gfortran v11.2.0 on my mac. there are 3 places with an integer/real mismatch in subroutine arguments. this isn't our code - i'm guessing from the directory and name that it's used to perturb synthetic radar obs for testing/experiments. there are probably no makefiles that use this module but the new build system tries to compile everything and fails the wrf build because of this. i took a quick stab at trying to see if i could resolve the real(4) vs integer(4) mismatch but it wasn't simple to see what could be changed without breaking the code.

There is a script to compile this code:
`DART/models/wrf/experiments/Radar/IC/sounding_perturbation/compile_pert_sounding.csh `. It does not compile on main with gnu/11.2.0

```
hkershaw@cheyenne5:/glade/scratch/hkershaw/DART/Bugs/mismatch/DART/models/wrf/experiments/Radar/IC/sounding_perturbation(main)$ gfortran -c pert_sounding_module.f90 
pert_sounding_module.f90:175:27:

  175 |       amp(m) = mag*gaussdev(iseed1)
      |                           1
Error: Type mismatch in argument ‘idum’ at (1); passed REAL(4) to INTEGER(4)
pert_sounding_module.f90:179:34:

  179 |          phs(m) = 2.0*PI*(2.0*ran2(iseed2)-1.0)
      |                                  1
Error: Type mismatch in argument ‘idum’ at (1); passed REAL(4) to INTEGER(4)
pert_sounding_module.f90:192:25:

  192 |       q(k) = mag*gaussdev(iseed1)
      |                         1
Error: Type mismatch in argument ‘idum’ at (1); passed REAL(4) to INTEGER(4)
hkershaw@cheyenne5:/glade/scratch/hkershaw/DART/Bugs/mismatch/DART/models/wrf/experiments/Radar/IC/sounding_perturbation(main)$ gfortran --version
GNU Fortran (GCC) 11.2.0
```
 I will move this to an issue, I think fix or remove this code from the repo, set as EXCLUDE  in this pull request

_Originally posted by @hkershaw-brown in https://github.com/NCAR/DART/issues/348#issuecomment-1127733514_

**Comment by hkershaw-brown** [comment]
`wrf/WRF_DART_utilities/advance_cymdh` has iargc interface  (now an instrinsic). 

```
 interface
    integer function iargc()
    end function iargc
 end interface
```

```
wrf/WRF_DART_utilities(main)$ gfortran advance_cymdh.f90 
/usr/bin/ld: /glade/scratch/hkershaw/ccck4UxM.o: in function `MAIN__':
advance_cymdh.f90:(.text+0x1ab): undefined reference to `iargc_'
collect2: error: ld returned 1 exit status
```
"In new code, programmers should consider the use of the [COMMAND_ARGUMENT_COUNT](https://gcc.gnu.org/onlinedocs/gcc-4.2.4/gfortran/COMMAND_005fARGUMENT_005fCOUNT.html#COMMAND_005fARGUMENT_005fCOUNT) intrinsic defined by the Fortran 2003 standard."

**Comment by mgharamti** [comment]
@hkershaw-brown Good catch! Do we get past this with other compilers? I'm just surprised this was sitting in our code without anyone reporting it.

**Comment by hkershaw-brown** [comment]
@mgharamti  The newer versions of compilers are more strict about the fortran standards so in the last year or so we've started to hit problems, particularly with the "argument mismatches" (e.g. https://github.com/NCAR/DART/issues/158)

One of the goals of having the new build system is to make it easier to find code that is causing problems, so mission accomplished :grimacing:  I guess.
I think for a couple of the wrf utilities it has been some time since anyone compiled them.
