### ISSUE TITLE
Bug: clouds flipped up/down in RTTOV for IR/VIS

### ISSUE THREAD

**Issue by lkugler** [NCAR/DART#365]
Hi Helen,
I showed you an inconsistency yesterday ([figure 1: before change](https://user-images.githubusercontent.com/29361544/176202803-36127c0e-6ffc-4aaf-af49-ab4161a750ee.png)), that is, differences between the python interface (my script) and the DART(Fortran) interface to RTTOV. Yesterday I thought my script is wrong but now I think differently. I looked at a gridpoint with a large difference (0.29 vs 0.96 reflectance) and the cloud water/ice profiles seem to be flipped up-down, because

1. The profiles initially showed ice clouds lower than water clouds, which is very suspicious (colder ice clouds should be above), see image 2
2. The clouds were quite high in the stratosphere where no clouds should be ([figure 2](https://user-images.githubusercontent.com/29361544/176200254-9007b5b9-be37-4965-a243-9fdfa4507075.png))
3. I unflipped the arrays in DART(Fortran) and now there are almost no differences anymore ([figure 3: after change](https://user-images.githubusercontent.com/29361544/176202189-07b58068-f907-46fc-8d5a-bea5f5cefffc.png))  

### Reason
- RTTOV uses a top-of-atmosphere-to-bottom convention while WRF uses the reverse.
- `obs_def_rttov_mod.f90` flips the array once for cfrac, pressure, temperature (correct)   
but twice for cloud variables (wrong): once when putting clouds into an intermediate variable `totalwater` / `totalice` and a second time when putting totalwater into the RTTOV input variable

### Summary
- I think there is a bug concerning RTTOV with clouds for IR/VIS channels.
- The results can be severely different in some cases. In most cases, the differences were small. Probably because the bug is less bad for deep clouds (dense cloud from the lower to higher layers) and worst when there are just high or just low clouds.

I'm sorry that this bug slipped through testing in 2020. I just found it by calculating obs on a grid and comparing the output from the two interfaces.
Lukas

**Comment by hkershaw-brown** [comment]
Thanks for this bug report Lukas

**Comment by lkugler** [comment]
[The changes are here (commit)](https://github.com/NCAR/DART/commit/d4d5d9d89e23a9c8cd3e3b11d9be6b695a1c033f)
