### ISSUE TITLE
bug: Objects accessed via a getter are exposed to changes

### ISSUE THREAD

**Issue by fdom68** [NCAR/DART#372]
:bug: Your bug may already be reported!
Please search on the [issue tracker](https://github.com/NCAR/DART/issues) before creating a new issue.

### Describe the bug

Class A has a private attribute instance of class B, let's say _b. A getter on _b is also defined.

class A {
   final B _b;
   B get b => _b;
}

The getter b is used in class C (the client), and is assigned a value;

class C {
  void getB() {
       final A a = A();
       a.b = x;         // an error is raised by the compiler
  }
}

An error is raised, which is totally correct.
The error says "There isn’t a setter named 'b' in class 'A'". Good.

Now, let's define an integer _d as a private attribute of B, and d  the getter on _d.

class B {
   final int _d;
   int get d => _d;
}

If now we modify the client C in the following way, then the attribute _d is modified and no errors is notified to the developer:
class C {
  void getB() {
       final A a = A();
       a.b.d = 100;         // No error is raised by the compiler and  b is modified
  }
}

I would expect here an error message too from the compiler. 
This is rather a major vulnerability since it exposes objects to changes.

### Error Message  
No error message is raised
### Version of DART      
Which version of DART are you using? 
You can find the version using `git describe --tags`  
2.17.3
### Have you modified the DART code?   
No  

### Build information
Please describe:  
 1. The machine you are running on (e.g. windows laptop, NCAR supercomputer Cheyenne).   
  windows laptop
 3. The compiler you are using (e.g. gnu, intel).

**Comment by hkershaw-brown** [comment]
Hi @fdom68,

I think you may be looking for [dart-lang](https://github.com/dart-lang).
This is [DART](https://dart.ucar.edu/), the Data Assimilation Research Testbed. Do get back in touch if you are ever interested in ensemble data assimilation. 

Cheers,
Helen
