### ISSUE TITLE
the rank histogram calcluation in matlab code

### ISSUE THREAD

**Issue by hgrhgy** [NCAR/DART#373]
Is `handles.ens_size` sholud be `handles.model_size`  for the shape of `handles.posterior` or `handles.prior` is defined as (time, model_size, ens_size)?

https://github.com/NCAR/DART/blob/cbe0d41e9ce190366b3cc5cc1433becf2ebc421c/guide/DART_LAB/matlab/run_lorenz_96_inf.m#L1321

and 

https://github.com/NCAR/DART/blob/cbe0d41e9ce190366b3cc5cc1433becf2ebc421c/guide/DART_LAB/matlab/run_lorenz_96_inf.m#L1458

**Comment by hkershaw-brown** [comment]
Thanks for reporting this @hgrhgy, we'll take a look.

Note same for run_lorenz_96.m:

https://github.com/NCAR/DART/blob/cbe0d41e9ce190366b3cc5cc1433becf2ebc421c/guide/DART_LAB/matlab/run_lorenz_96.m#L847-L851

compare to 

https://github.com/NCAR/DART/blob/cbe0d41e9ce190366b3cc5cc1433becf2ebc421c/guide/DART_LAB/matlab/run_lorenz_96.m#L804-L808

**Comment by mgharamti** [comment]
@hgrhgy Thanks for the catch! 

Indeed, the limit on the index counter for both prior and posterior rank calculations should be `handles.model_size` **not** `handles.ens_size`. This also applies to the same `for` loops in `run_lorenz_96.m` 

Though, just to clarify, this bug fortunately did not cause any problem in the other plots (e.g., RMSE, spread, inflation, etc). It's only confined to the rank histogram plots. The bug fix would reflect an accurate frequency (y-axis) on the prior and posterior RH panels.

**Comment by hgrhgy** [comment]
@hkershaw-brown @mgharamti thanks for replying. I found this by setting the `ens_size=80`.
I have test it in both cases. It seems the shape of rank histogram doesn't change much.

**Comment by hkershaw-brown** [comment]
fixed by https://github.com/NCAR/DART/pull/375
