### ISSUE TITLE
no documentation for netcdf_utilities_mod

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#378]
30 or so public routines in netcdf_utilities_mod

1. We allow start, count, stride, & map but _not_ scale and offset?  It looks like start, count, stride came in when Jeff Steward was working on GITM https://github.com/NCAR/DART/commit/a29afbf6e4e1290932dfe2439e040329fa8fc703

2.  What happens with unlimited dimensions?

     e.g If you call nc_get_double_2d on a file that has an unlimited Time dimension, is this 

    `x,Time`      1D variable?
    `x,y,Time `   2D variable?
 
    Does nc_get_double read the last time if x,y, Time ?
 
    e.g cam-fv model_mod https://github.com/NCAR/DART/blob/cc1da67976feb3b092ac9eae7388f6181ef33154/models/cam-fv/model_mod.f90#L2032

    ```
    integer :: cam_date

    ! CAM initial files have two variables of length 
    ! 'time' (the unlimited dimension): date, datesec

     call nc_get_variable(ncid, 'date',    cam_date, routine)
     call nc_get_variable(ncid, 'datesec', cam_tod,  routine)
     ```

    what is this reading if the variables have length time? Are you reading the 1st value along the time dimension?

Probably related: https://github.com/NCAR/DART/issues/359

**Comment by hkershaw-brown** [comment]
What is the reason dart limiting the number of dimensions a netcdf variable can have (4)?

https://github.com/NCAR/DART/blob/477409d6191d93fb155c4934252bfc15ba824c6d/assimilation_code/modules/utilities/netcdf_utilities_mod.f90#L1033-L1035

**Comment by nancycollins** [comment]
i honestly don't remember.  fortran limited arrays to rank 7 for a long time, although i guess it's now 15?   it might be that i was thinking we should only add support for higher dim arrays if they were actually needed.  it seems less common to have rank 5 arrays in geophysical model arrays, and even less 6 or 7.  early on i made wrappers for each dim (1,2,3,4 ...) but now it's only 1d and Nd (the 1d couldn't be overloaded with the other) so it's not increasing the number of subroutine entry points to support more than 4d arrays.  if there's a use for it, take out the limit.

**Comment by hkershaw-brown** [comment]
Oh no imminent need to rip out the limit, just wanted to check if I was missing some dart limit. 
I was wondering if it was anything to do with time, member dims, but I do not think that is the case.

Also side note Nancy - think on this, can we use elemental to have a function deal with scalars and arrays?

**Comment by hkershaw-brown** [comment]
closing inactivity
