### ISSUE TITLE
CICE parameter estimation support

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#38]
Ed note: This issue was originally reported 28 June 2020 and is being manually ported over to GitHub.

> I also had to do a bit of hacking to _dart_to_cice.f90_ to make the code run without parameter estimation. It was hard wired to do it. I made it turn on/off with a namelist parameter now. It would be good to update it in the code base someday.

I agree ... volunteers?

**Comment by hkershaw-brown** [comment]
closing, unclear who has this code.  
Can reopen in the future.
