### ISSUE TITLE
bug: cam-fv no_normalization_of_scale_heights   = .false.

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#381]
:bug: Your bug may already be reported!
Please search on the [issue tracker](https://github.com/NCAR/DART/issues) before creating a new issue.

### Describe the bug

1. List the steps someone needs to take to reproduce the bug.  

build with debugging flags
cam-fv filter run with
```
   no_normalization_of_scale_heights   = .false.
 ```

Test case is here: /glade/scratch/hkershaw/DART/pull_requests/pull_370/test_cam.main2

3. What was the expected outcome?
Successful run of filter

5. What actually happened?  
error: ptype being used without being defined.

### Error Message  
Please provide any error messages.

```
forrtl: severe (194): Run-Time Check Failure. The variable 'model_mod_mp_obs_vertical_to_scaleheight_$PTYPE' is being used in '/glade/scratch/hkershaw/DART/pull_requests/pull_370/DART.main/models/cam-fv/model_mod.f90(3471,33)' without being defined
Image              PC                Routine            Line        Source             
filter             00000000004B6CF7  model_mod_mp_obs_        3471  model_mod.f90
filter             00000000004B5EE4  model_mod_mp_conv        3302  model_mod.f90
filter             00000000006007E2  assim_tools_mod_m         478  assim_tools_mod.f90
filter             00000000006D6DD0  filter_mod_mp_fil         918  filter_mod.f90
filter             000000000065C15B  MAIN__                     20  filter.f90
filter             00000000004077A2  Unknown               Unknown  Unknown
libc-2.22.so       00002AC391147A35  __libc_start_main     Unknown  Unknown
filter             00000000004076A9  Unknown               Unknown  Unknown


```

In obs_vertical_to_scaleheight

ptype is only defined in the no_normalization_of_scale_heights = .true. part of the if statement, here:
https://github.com/NCAR/DART/blob/0de0a8aa25ddbec49b3b278a19ad4136eb829322/models/cam-fv/model_mod.f90#L3422-L3430

Here is ptype being used in  no_normalization_of_scale_heights = .false. part of the if statement. 

https://github.com/NCAR/DART/blob/0de0a8aa25ddbec49b3b278a19ad4136eb829322/models/cam-fv/model_mod.f90#L3471

I'm not sure you need to check ptype, because VERTISSURFACE obs is checked in the surrounding if statement, so by line 3471 ptype can only be QTY_PRESSURE. 

``` diff
- 3471    if (ptype == QTY_PRESSURE .and. is_vertical(location, "PRESSURE")) then
+ 3471    if is_vertical(location, "PRESSURE") then
3472        pressure_array(:) = query_location(location, "VLOC")
3473       my_status = 0
```

### Which model(s) are you working with?
cam-fv

### Version of DART      
Which version of DART are you using? 
You can find the version using `git describe --tags`  
v10.0.5

### Have you modified the DART code?   
No  

### Build information
Please describe:  
 1. Cheyenne
 2. intel

**Comment by kdraeder** [comment]
It seems to be true that the ptype test could be taken out of
- 3471    if (ptype == QTY_PRESSURE .and. is_vertical(location, "PRESSURE")) then
but I lean toward moving lines 3426-3431 to before the first if-test,
so that ptype is defined no matter what.  Then it could also be used 
in the .not.no_norm section too instead of another query_location.

Related; the logic of using query_location(location) 
to define  ptype, then also using is_vertical(location, "PRESSURE") 
to decide how to convert it,
seems needlessly complicated andor misleading.

Moving the lines would also help with another problem I seem to see with this subroutine;
it's assuming that location can have only VERTISPRESSURE or 
VERTISSURFACE.  But it appears to me that this location can be
from a potentially close ob (not state) in get_close_obs, 
which can have other vertical types, like  VERTISHEIGHT (e.g. GPS).
But I think that can't happen if convert_all_obs_verticals_first = .true. 
(the default value).  What's the value in your test?  The answer should be in the da.log file: "Converting all observation verticals to localization coordinate first."

Maybe this is nitpicking, or belongs in a separate issue,
but wouldn't it follow our coding style/standards more closely
if scaleheight_val was defined in the no_normalization_of_scale_heights section
using the scale_height function?
Same for the VERTISSURFACE section of the 
.not.no_norm section.

**Comment by hkershaw-brown** [comment]
convert_all_obs_verticals_first = .true. in my test.

Note the refactoring of cam-fv is out of scope for me at the moment, so I'm not disagreeing with your nitpicking (just overlooking it for now 😄 )
The main goal is to get cam-se released (which comes as a package deal with cam-common-code).

**Comment by nancycollins** [comment]
this routine is not assuming that vert is only pressure or surface.  it has those as an initial test because there is a fast way to compute scale height for those.  if it is something else it interpolates to pressure, so there is code to take care of verts in height and level.

**Comment by nancycollins** [comment]
about is_vertical and ptype - those are separate things.  ptype is a quantity type and has nothing to do with what the vertical coordinate of any location is.

**Comment by kdraeder** [comment]
> 

I just realized that I was tracing the error up through the calling tree and getting somewhat lost in the calls to get_close_XXX.  I couldn't see how any ob or state coming from those could need converting and run into the error.  Now I realize that it's probably hitting the error through the 
convert_all_verticals_first call to convert_vertical_obs.

The test on both ptype and is_vertical is somewhat subtle,
so I still recommend leaving those tests as they are, 
and moving the definition of ptype out of the if-test on no_norm...
Nancy, you didn't object to that idea, or approve it.  Thoughts?

If we come back to refactoring this subroutine, I'd also want to figure out
if it's right to pass ptype to interpolate_values in the no_norm...=true section (ptype can have either QTY there), 
but pass QTY_PRESSURE to it in the no_norm...=false section.

**Comment by kdraeder** [comment]
> about is_vertical and ptype - those are separate things. ptype is a quantity type and has nothing to do with what the vertical coordinate of any location is.

To me they look connected  by
   if (query_location(location) == VERTISSURFACE) then
      ptype = QTY_SURFACE_PRESSURE
since is_vertical returns a true/false based on the which_vert of the location,
and query_location returns the which_vert itself.

**Comment by nancycollins** [comment]
sure, they are "connected" but they are still totally different things.  

QTY_xx is a quantity, and it's going to be used in an interpolate() call.  

is_vert() is looking at what type of coordinate the vertical location value is -  VERTISSURFACE, VERTISPRESSURE, VERTIS...  which is the fortran equivalent of an enumerated value.  if the vertical coordinate is already a pressure type, the value of the vertical location can be used without interpolating that location in the field for it.  if not, the field it will be interpolated in is the QTY_PRESSURE field.

**Comment by nancycollins** [comment]
not setting ptype in the else statement is clearly a bug and sure, the fix is to move the test outside of the if statement.
