### ISSUE TITLE
obs_converter run_tests.csh upgrade

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#4]
The obs_converter/run_tests.csh  runs preprocess twice, basically. Once in the quickbuild.csh and then again during the 'run' portion of the script.

Also need to have separate input.nml.testing scripts for some converters. Some converters have hardcoded output names that do not match the input.nml examples in the converters' work directory.

**Comment by timhoar** [comment]
Currently the testing suite takes 45 minutes to an hour, so cutting down the time is worthwhile.

**Comment by hkershaw-brown** [comment]
merged this issue into #133
