### ISSUE TITLE
Redundant, expensive array initializations in the mpas_atm model_mod.f90

### ISSUE THREAD

**Issue by mjs2369** [NCAR/DART#405]
In model_mod.f90 for mpas_atm, there are two arrays, close_ind and dist, that are created and initialized in the get_close_state and get_close_obs methods to values that indicate a missing status for all indices in the array. 

https://github.com/NCAR/DART/blob/7ee9ed9c86330ba231fa29395dbb2db47d3a7e80/models/mpas_atm/model_mod.f90#L1994
https://github.com/NCAR/DART/blob/7ee9ed9c86330ba231fa29395dbb2db47d3a7e80/models/mpas_atm/model_mod.f90#L1995

Profiling results show that these lines use a significant portion of the runtime, particularly in the get_close_state subroutine in which line 1994: close_ind = -99 and line 1995: if (present(dist)) dist = 1.0e9_r8 are %4.3 and %15.1 respectively. 

<img width="1426" alt="Screen Shot 2022-10-03 at 6 11 15 PM" src="https://user-images.githubusercontent.com/44214771/194124874-7d8af91a-2698-41f6-b316-e60e8bdc6ab8.png">

These initializations can cause mpas_atm executions of filter to take a significantly longer runtime to complete, especially for cases with a large model_size.

Solution:
After examining the code, it was determined that these initializations are entirely unnecessary, as there is no place where the values in the arrays are compared to the missing status values that they are set to in these lines.

Due to the close_ind and dist’s declared intent(out) in the get_close_x subroutines, new arrays are automatically created and set to default initialization values (random values, typically 0) at each call to get_close_x, and therefore there is no need to overwrite values from the previous call to get_close_x. 

So these initializations turn out to be redundant; there is no need to use this specific missing value over the values that are automatically put into the array. 

Results:
This was tested and shown to be bitwise identical for multiple mpas_atm test cases, using both Intel and GNU Fortran compilers, proving these initializations to be unnecessary.

For an execution of a high-memory case on Casper (96 ensemble members, 459,985 observations, model_size = 327,759,048), the runtime was reduced from 145 min. to 112 min. or about %23

For an execution of separate mpas_atm case that uses RTTOV  observations (10 ensemble members, 77,042 observations, model_size = 109,118,772), the runtime is reduced from 1 min. 9 sec. to 55 sec. or about %20

### Which model(s) are you working with?
mpas_atm

### Version of DART      
v10.5.1

### Build information
Please describe:  
 1. NCAR supercomputer Cheyenne, Casper   
 2. All compilers (GNU, Intel)

**Comment by hkershaw-brown** [comment]
fixed in #407
