### ISSUE TITLE
bug: model_mod_check segfaults in create_state_window

### ISSUE THREAD

**Issue by mjs2369** [NCAR/DART#413]
:bug: 

### Describe the bug

1. List the steps someone needs to take to reproduce the bug.  
```
cd models/WRF/work
./quickbuild.sh
./model_mod_check
```
NOTE: any model can be used but either WRF or a lorenz model will be the easiest.

2. What was the expected outcome?
successful run of model_mod_check

3. What actually happened?  
segfaults during TEST 4, in the create_state_window() subroutine in DART/assimilation_code/modules/utilities/null_win_mod.f90

### Error Message  
<img width="1200" alt="Screen Shot 2022-10-12 at 3 07 22 PM" src="https://user-images.githubusercontent.com/44214771/195448202-7eddbe67-3306-4608-84fb-6821eced62e4.png">

### Which model(s) are you working with?
Any model

### Version of DART      
v10.5.2

### Have you modified the DART code?   
No

### Build information
Please describe:  
 1. The machine you are running on (e.g. windows laptop, NCAR supercomputer Cheyenne).   
 2. The compiler you are using (e.g. gnu, intel).  
Any machine, any compiler

**Comment by hkershaw-brown** [comment]
Hi Marlee, 
Can you try running with mpi
`mpirun -4 ./model_mod_check`
to see if you are running out of memory

**Comment by mjs2369** [comment]
> 

Ouch, that makes me feel foolish. Deleting this issue then cause model_mod_check worked all the way through. Should've though to give that a try first. 

Thanks Helen!

**Comment by hkershaw-brown** [comment]
Don't feel foolish, it is always to good bring something up it seems weird. Particularly since we have netcdf problems (caused by me) which will trip up model_mod_check 

pull #403 will fix the netcdf read problem. I want to run one last test with TIEGCM.

Cheers,
Helen

**Comment by mjs2369** [comment]
@hkershaw-brown can you delete this issue? It says that the button to delete should be under Notifications on the right side bar, but I don't think I have the option because I'm not an admin.

If you can't do it either, we can just close it.
