### ISSUE TITLE
bug: Running perfect_model_obs in parallel

### ISSUE THREAD

**Issue by mgharamti** [NCAR/DART#417]
:bug: Apologies if this has been reported. I couldn't find any past issues similar to this one. 

### Describe the bug
Running `perfect_model_obs` in parallel and serially produce different `obs_seq.out` files. Though, they both create the same truth file: `true_state.nc`. I ran into this issue while running hundreds of experiments using the lorenz_96 model. The assimilation results only make sense when using the `obs_seq.out` produced by the serial `perfect_model_obs`. One other interesting fact of this issue: If you compare `obs_seq.out` from both serial and parallel runs, you'll find that the first cycle has exactly the same truth and observation values. Differences only start to appear for subsequent cycles (see attached screenshot). 

Not sure if this is a known behavior or whether it's related to my compiler. I vaguely remember someone telling me not to run `perfect_model_obs` in parallel in the bgrid model. But that was long time ago and not lorenz_96. 

### Error Message  
No error

### Which model(s) are you working with?
Lorenz 96

### Screenshots   
![Screen Shot 2022-10-26 at 4 51 28 PM](https://user-images.githubusercontent.com/35781176/198153484-5c79a093-11a1-4d8d-9668-f52d8cfae857.png)

### Version of DART      
Which version of DART are you using? 
v10.5.1

### Have you modified the DART code?   
No  

### Build information
 1. The machine you are running on: NCAR supercomputer Cheyenne.   
 2. The compiler you are using: intel.

**Comment by hkershaw-brown** [comment]
I guess this comment was correct for models advanced by DART then: https://github.com/NCAR/DART/commit/9435598393fac6fec9e9c1d762fd0ca2c927749e

It looks like the state window is created only once when the netcdf file is read  (not in advance_time do) so the forward operator is doing the same calculation over and over when you are using mpi.
