### ISSUE TITLE
Documentation update: consolidating and improving the documentation for porting new models to DART

### ISSUE THREAD

**Issue by mjs2369** [NCAR/DART#439]
In the DART documentation, there are multiple sections that cover the same material on how to use a new model with DART:
https://docs.dart.ucar.edu/en/latest/models/README.html#hints-for-porting-a-new-model-to-dart
https://docs.dart.ucar.edu/en/latest/guide/advice-for-new-collaborators.html#adding-a-dart-interface-to-a-new-model

These sections of the documentation need to be consolidated into one, and the content needs generally updated to improve clarity and organization and ensure that the procedure is completely up-to-date with the new model automation feature.

**Comment by johnsonbk** [comment]
This is a well-needed update to the documentation. We put together a simple DART style guide based off of the Google Developer documentation style guide here:

https://wiki.ucar.edu/display/DIME/Documentation+Style+Guide
