### ISSUE TITLE
documentation bug: prep_bufr.html is referenced, but no longer exists

### ISSUE THREAD

**Issue by kdraeder** [NCAR/DART#452]
### Describe the bug

1. List the steps someone needs to take to reproduce the bug.   In observations/obs_converters/NCEP, file prep_bufr.html is referenced in 3 files:

> README
> prep_bufr/README
> prep_bufr/work/README

3. What was the expected outcome?  It should exist in the NCEP directory tree.
4. What actually happened?  It has been replaced by prep_bufr.rst.  

### Error Message  
"File not found"

### Version of DART      
Which version of DART are you using? 
v11.0.0-alpha, but it extends back to commit 421fb836ca624e2f5f9354670d412b7e51fb19e6 

### Have you modified the DART code?   
No  
It's possible that references to other html files are still in various README (and similar) files,
which would be good to clean up all at once.

**Comment by hkershaw-brown** [comment]
The prep_bufr.rst gets built into the html documentation:
https://docs.dart.ucar.edu/en/latest/observations/obs_converters/NCEP/prep_bufr/prep_bufr.html

**Comment by kdraeder** [comment]
Oh yeah!  That doesn't occur to us Luddites.
Does it make sense to add that whole path to the references to prep_bufr.html?
Or a comment about the rst being converted to an html in the docs?

**Comment by hkershaw-brown** [comment]
or remove the README files?
