### ISSUE TITLE
bug: gathering namelists required by a program appears to not be working

### ISSUE THREAD

**Issue by kdraeder** [NCAR/DART#460]
### Describe the bug

1. List the steps someone needs to take to reproduce the bug.  
Run mkmf (`quickbuild.sh filter` is sufficient) in a {model}/work directory.
3. What was the expected outcome?
There should be a file containing the {module}_nml namelists from all of the modules which were used to build the executable.  It would be named input.nml.{executable}_default.
5. What actually happened?  
No collected namelist file appeared in the work directory.
I'm able to make a file appear by adding ", q/\.nml/" to @src_suffixes in mkmf.

### Error Message  
If .nml is added to src_suffixes, then 
1) the build fails with 
   "quad_utils_mod.nml: Permission denied
     Makefile:12: recipe for target 'quad_utils_mod.o' failed",
   or quad_utils is not available later when it's needed during the compiling model_mod.

2) the input.nml.{executable}_default file is created, but contains the contents of all of the .nml files in work, 
    as well as the desired {component}_nml namelists.  The resulting redundant _nml entries in input.nml 
    should be avoided.

### Which model(s) are you working with?  
cam-fv 

### Version of DART      
v9.8.0-3038-g8540de2c0, cloned from https://github.com/jlaucar/DART.git

### Have you modified the DART code?   
Yes, while trying to fix this (see above), but not otherwise.
I did not find any tools (except mkmf) which could be used to collect _nmls.

### Build information
Please describe:  
 1. The machine you are running on
  Cheyenne  
 3. The compiler you are using (e.g. gnu, intel).  
    intel.linux (but it appears to be a mkmf functionality issue, not a compiler issue)

**Comment by hkershaw-brown** [comment]
just to clarify, this was closed because it is not reproducible, that is the .nmls are collected and output as input.nml_{executable}_default. 

There are two options when closing an issue:

![Screen Shot 2023-03-07 at 10 09 52 AM](https://user-images.githubusercontent.com/20047007/223463103-07aaf5be-2217-4a15-8ed9-938e75981f17.png)

I'll try and close issues with explicit comments to be more clear about this in the future.

Cheers,
Helen
