### ISSUE TITLE
Feature request: Experiment setup for TIEGCM  

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#511]
### Use case  
What are you trying to accomplish?  Sometimes there may already be a way to do what you need.  

Set up experiments for the NASA-TIEGCM team: https://ccmc.gsfc.nasa.gov/
PMO, filter for a given date range.

There is https://github.com/NCAR/DART/issues/469 hanging out which should be pulled into the experiment setup. 

### Is your feature request related to a problem?  
We don't really have out-of-the box setups that I can point people to when setting up a cycling experiment for a large model. 
Particularly for PMO.
There is https://github.com/NCAR/DART/tree/main/observations/obs_converters/even_sphere
which is for synthetic  radiosondes

### Describe your preferred solution  

Python  to set up and run the experiment:
  -  setup experiment directory
  - setup assimilation time windows
  - synthetic observation sequence files 
 - create batch scripts for the model, and for PMO, filter
 - submit the jobs ( step through each assimilation cycle)

### Describe any alternatives you have considered  
It would nice to not have the setup scripts be model specific. 
For now, focusing on the TIEGCM-NASA deliverable.

**Comment by hkershaw-brown** [comment]
```
./obs_seq_to_netcdf
loc = ncread('obs_epoch_001.nc', location);
scatter(loc(1,:), loc(2,:), loc(3,:))
```

![Screen Shot 2023-07-13 at 9 41 47 AM](https://github.com/NCAR/DART/assets/20047007/10b7fff5-c88c-4384-937f-8ccfbc6724b7)

**Comment by mgharamti** [comment]
These look like the olympic rings to me. I don't know how to interpret them. @hkershaw-brown is there any issue with `'obs_epoch_001.nc'` or is this the behavior you expect?

**Comment by hkershaw-brown** [comment]
@mgharamti no issue I just did a 2d scatter plot instead of 3d and you get a ripple which entertained me.
The correct plots are in there too.

**Comment by hkershaw-brown** [comment]
This is up and running. There is no perturbing.

Met with CCMC and CU Boulder people. Just getting the original TIEGCM-DART shell scripts for cycling filter as a deliverable, so not putting these python setup scripts into DART and closing this issue for now.

https://github.com/NCAR/DART/tree/nasa-cycle
Archived here also  https://github.com/hkershaw-brown/DART/tree/nasa-cycle

May resurrect some of this for CROCODILE.
