### ISSUE TITLE
advancing the model inside PMO

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#52]
**Ed note: This issue was submitted by email.**

>Now I am trying to run the OSSE, namely, the perfect_model_obs experiments. When I went to the step 2, running ./perfect_model_obs gives the follwing errors:
>
> PE 0: filter:
>  routine: filter:
>  message: advancing the model inside PMO and multiple file output not currently supported
>  message: ... support will be added in subsequent releases
>  message: ... set "single_file_out=.true" for PMO to advance the model, or advance the model outside PMO
application called MPI_Abort(comm=0x84000000, 99) - process 0
>[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=99
>:
>system msg for write_line failure : Bad file descriptor

**Comment by timhoar** [comment]
There are two things about this message:
1. _perfect_model_obs_ should not be reporting that the error came from _filter_
2. the message is correct, but to explain _why_ `advancing the model inside PMO and multiple file output not currently supported` and how to avoid it - is a much larger issue.

When the observations within a single assimilation window are assimilated and the state is updated, the observation sequence file is queried to see if there are more observations. If there are more observations, the model is advanced and the cycle continues. The Manhattan version of DART allows subroutine-callable models (_lorenz_63, bgrid_solo_ and others) to continually update the same output files (_analysis.nc, filter_output.nc, perfect_output.nc, preassim.nc, true_state.nc_) with all the timesteps.
The `input.nml:perfect_model_obs_nml:single_file_out = .true.` is supported for these models.
This is what is meant by 'single_file' ... a single file has the output for all the timesteps.

Models that are **not** subroutine-callable must have `input.nml:perfect_model_obs_nml:single_file_out = .false.` (which is the default). The output files for these models are only allowed to have a single timestep in them - we have plans to support multiple timesteps, but this feature is not currently available.

**NOTE:** The `filter` program has these same restrictions; the `single_file_out` namelist variable appears in both the _perfect_model_obs_ and _filter_ namelists.

It is very common practice to have the observations for a single assimilation cycle in separate files.
User-supplied scripting then links the appropriate observation sequence file to `obs_seq.[in,out]` and _perfect_model_obs_ or _filter_ reads in just those observations, does what it needs to do, writes out the output files - and stops. The scripting then renames the files with some date/time and then, if needed, advances the model to the next assimilation cycle and links the next observation sequence file ... There are many examples throughout the _DART/model/*/shell_scripts_  directories for many models and queueing systems.

**Comment by chmod444** [comment]
Hello Tim,

Thanks for the detailed instructions.
The problem occurred in the call advance_state in ${DART}/assimilation_code/programs/perfect_model_obs/perfect_model_obs.f90.

    _if(ens_handle%my_pe == 0) call advance_state(ens_handle, 1, next_ens_time, async, …_

where the subroutine advance_state is in the ${DART}/assimilation_code/programs/perfect_model_obs/perfect_model_obs.f90.  The subroutine advance_state is performed in the following 3 main steps:

step 1: advance the wrf model to the target_time
    _rc = shell_execute(trim(adv_ens_command)//' '//trim(system_string)//' '//trim(control_file_name))_
    where the _adv_ens_command_ is _../shell_scripts/advance_model.csh_

step 2: read in the wrf states, including the ens_time, from the wrfinput_d01 file
    _call read_state(ens_handle, file_info_input, read_time_from_file, ens_time)_

step 3: check that the wrf model is advanced correct     
     _if (ens_time /= target_time) then
         "Model advance complete but model time not correct"
         …
     endif_

Errors occured in step 3, the message is the following:

   **PE 0: advance_state Model advance time is now:              day=  152487 sec=   0
   PE 0: advance_state Model advance time NOT what requested:  day=  152487 sec= 21600
   ERROR FROM:
   PE 0: advance_state
     routine: advance_state
     message: Model advance complete but model time not correct**

My first question is:
     The target_time is calculated as model_time + time_step, where time_step is determined by the wrfinput_d01 file (wrf%dom(1)%dt), whichs is 6 h (21600 s).  After running WRF model outside PMO, ens_time is read from the wrfinput_d01. However, ens_time should be "day=  152487 sec=   0" unless wrfinput_d01 is replaced by another file such as wrfrst* file at the target_time. Does this mean that wrfinput_d01 file should be updated between step 2 and step 3? If so, the wrfinput_d01 should be replaced by wrfrst* file once the ./wrf.exe is completed. Am I right?

My second question is:
      However, if the wrfinput_d01 file is replaced by wrfrst* file by the "_../shell_scripts/advance_model.csh_" script once the _./perfect_model_obs.exe_ is completed, how is the assimilation experiment performed by _./filter.exe_? To be specific, the execution of _./filter.exe_ will also use the "_../shell_scripts/advance_model.csh_" script. In OSSE, a perturbation run (or experiment) should be performed with the simulated observations under evaluation added to the wrfinput_d01. After the execution of _./perfect_model_obs.exe_, and when I want to perform the ./filter.exe, how should the wrfinput_d01 file be set in the "_../shell_scripts/advance_model.csh_" script?

Could you please give some suggestions?
Any replies would be highly appreciated!

Yongbo

**Comment by timhoar** [comment]
Hello Yongbo,

The DART wrf/tutorial/README.md    https://github.com/NCAR/DART/tree/master/models/wrf/tutorial
has excellent examples and provides a lot of information about running a DART experiement for a couple cycles.
This should answer your questions about timestepping and file motion.
You should definitely work through this before attempting anything more complicated.
