### ISSUE TITLE
Individual Member CESM hindcast development

### ISSUE THREAD

**Issue by kdraeder** [NCAR/DART#53]
Giovani Conti (CMCC) wants to know about the possibility
of running the hindcast ensemble one at a time,
to avoid the MPI(? or other resource) problem they're seeing
with larger (~40) ensembles.

Background:

Multi-instance means that CESM runs all the instances at the same time.
CESM can run multi-instance 2 ways; multi-coupler and single coupler.
Single-coupler is very inefficient (all the instances communicate 
through a single coupler), so we never use that.
We've been using multi-coupler for years; each instance has it's own coupler.
That was developed initially by Raffaele Montuoro.
We and CESM don't have a way to run each instance separately (either in succession
or as separate, parallel jobs), which would be useful for people 
 1. on small clusters
 2. having problems with large ensembles on big clusters, 
 3. with very large model states (e.g. 1/10th degree POP).

That's not many people, but they pop up occasionally, 
so we need to discuss how to handle it.

George Modica developed sequential ensemble hindcasting for for WACCM in Lanai.
Kevin has found his scripts, which should be added to DART somewhere.
? They're not consistent with Manhattan or CESM2,
  so how should that be handled?

Tim wonders about identifying the actual command that CESM uses to run jobs.
The command andor script was hidden in CESM1, but Kevin found it at one point.
Now (CESM2) the command andor script is generated by python scripting
and will take some unravelling to identify.  That code is mostly in
${CESM}/cime/scripts/lib/CIME/case:"case.run" and ${CASEROOT}/.case.run (and ...?).
This might be useful for running job arrays.

WRF runs it's member hindcasts as completely separate jobs (not even job arrays)
and keeps track of how they finish.  Then it runs a separate assimilation job.
That makes for complicated scripting, but if any members fail, they can be
re-run individually, which saves core hours.

Strategy Possibilities:

1. Don't bother with this, but help CMCC get their assimilation working.
2. Adapt Modica's sequential hindcasts to Manhattan and CESM2.
3. Figure out a job array architecture to do the hindcasts separately but in parallel.
4. Like WRF; parallel, completely independent member hindcasts.
5. ?

(KDR: Github (in Firefox) won't let me assign more than 1 person to this,
which I've successfully done in PRs.  Also, I don't see a place to add watchers.)

**Comment by kdraeder** [comment]
Gio has developed new scripts to run the CAM hindcasts separately.  
From a powerpoint:
In order to create a workaround for the issues related to
1. the Infiniband bugs (that brings mpi_finalization problems both for CESM2 and DART)
2. small cluster often overcrowded
we have created a small suite of scripts that decouple CESM2 and DART and allows for the creation and run of the experiments. The CESM2 members run in different jobs.
The suite is in a GitHub repository ( https://github.com/giovanniconti83/suite_assimilation- atmo-CMCC )
Lots of files must be “cleaned” and some functionality like compression must be added. We hope that this could help also someone else in the future that has to work on a small intel cluster...

**Comment by kdraeder** [comment]
The powerpoint outlines the software and is ~2 Mb.
Should I attach it?  Or just directly related parts?

**Comment by hkershaw-brown** [comment]
@kdraeder  the  https://github.com/giovanniconti83/suite_assimilation repo appears to be private.  
You could share the power point in google drive with the DAReS team maybe?

**Comment by kdraeder** [comment]
The outline of their workflow is now in the DART Google Drive:
[suite_assimilation_atmo_CMCC.pdf](https://drive.google.com/drive/folders/1rKmU8jJs8RUBXr1psdxsM22Nnk4gwnWU?ths=true)

I'll ask about accessing the suite_assimilation repo.

**Comment by kdraeder** [comment]
The separated hindcasts mode seems to be working, but they are seeing puzzling results when 
running just the assimilation and varying the number nodes(processors)
while keeping the number of of members and observations (~600,000 ) the same.
The performance improves as the number of nodes increases from 
"much less than the number of members" to roughly the number of members.
Then performance mostly gets worse.  My understanding is that filter should continue
to run faster as more processors are added and there shouldn't be anything magic
about the number of nodes approaching the number of members.  
(I'd add a picture, but github doesn't want to upload an eps file.  
I'll put it on the G-Drive if that would be useful.)

The question of the moment is whether I should tell them to consult their systems people
to look for compiler or communications issues, or should I poke around in Gio's timing experiments 
to look for clues.

**Comment by nancycollins** [comment]
hi kevin.  do you have one of their filter log files?  and do they have the timing on?  (filter_nml::output_timestamps = .true.)  it would be interesting to know how much time is spent in the forward operators compared to the assimilation step.  that would change what to look at optimizing.   for example, as you add processors the forward operator time should continue to decrease, but if it's a small amount of the overall run time then that won't affect the results much.  if they're spending lots of time reading and writing input and output files, adding processors increases the communication time to gather and scatter data.  if the bulk of the time in the assimilation step itself, you could look at adding more bins to the location module, or seeing if they have distributed the mean or not (distributed takes less memory but runs slower; non-distributed is the opposite).

**Comment by hkershaw-brown** [comment]
assuming this is a zeus issue not a dart issue.
