### ISSUE TITLE
Add documentation to WRF-DART Tutorial diagnostics section

### ISSUE THREAD

**Issue by braczka** [NCAR/DART#543]
### Use case  
The WRF-DART Tutorial documentation gives a very brief and incomplete description of appropriate diagnostics to apply to determine  the skill of the tutorial assimilation.   I have been asked by end-users of WRF-DART how to apply the DART Matlab diagnostics to the WRF Tutorial.

### Is your feature request related to a problem?  
Lack of documentation of how to apply DART Matlab diagnostics to WRF-DART Tutorial.

### Describe your preferred solution  
I have generated a separate document that I will append to the existing WRF_DART Tutorial documentation.  This  provides instructions on how to operate on diagnostic files already generated during the tutorial.  This would require no additional work by the user, other than working with existing diagnostic files and DART Matlab scripts.   I have received positive feedback from users working with the CLM-DART tutorial diagnostic section, and I want to bring that to WRF.  Also the WRF tutorial uses a 'real world' example, so the diagnostics are actually quite realistic and relevant to real world applications.

### Describe any alternatives you have considered  
Do nothing.  The WRF code is being re-factored and there is a general movement away from using Matlab scripts as diagnostics.

**Comment by hkershaw-brown** [comment]
Fixed in https://github.com/NCAR/DART/pull/544
