### ISSUE TITLE
bug: quickbuild.sh errors out with the gnu compiler on Derecho (MPI errors)

### ISSUE THREAD

**Issue by mjs2369** [NCAR/DART#551]
### Describe the bug

1. List the steps someone needs to take to reproduce the bug.  
Run quickbuild.sh on any model on Derecho using the gnu compiler
 
2. What was the expected outcome?
Filter finishes successfully

3. What actually happened?  
Multiple MPI error messages (rank and type mismatches) are produced from mpi_utilities_mod.f90

### Error Message  
See screenshots

### Which model(s) are you working with?
All models

### Screenshots   
![image](https://github.com/NCAR/DART/assets/44214771/fbb2cf3a-621b-46f2-b1c5-bfd4f5db69da)
![image](https://github.com/NCAR/DART/assets/44214771/cae03511-0a42-4313-a5f9-2ceb833c2434)

### Version of DART      
Which version of DART are you using? 
v10.8.4

### Have you modified the DART code?   
No

### Build information
Please describe:  
 1. The machine you are running on (e.g. windows laptop, NCAR supercomputer Cheyenne).   
 2. The compiler you are using (e.g. gnu, intel).  

Derecho, gnu

**Comment by hkershaw-brown** [comment]
https://github.com/NCAR/DART/issues/261
