### ISSUE TITLE
bug: quickbuild.sh errors out on parse_args_mod.f90 on Derecho

### ISSUE THREAD

**Issue by ann-norcio** [NCAR/DART#555]
### Describe the bug

1. List the steps someone needs to take to reproduce the bug.  
On Derecho, run quickbuild.sh on any model using nvhpc compiler with mkmf.template.pgi.cray (suggested template to use since there is no existing nvhpc mkmf template currently; related to issue #554)

3. What was the expected outcome?
Quickbuild.sh runs successfully

5. What actually happened?  
Error messages are produced from parse_args_mod.f90

### Error Message  
See screenshots for error messages

### Which model(s) are you working with?
all models

### Screenshots   
<img width="1583" alt="Screen Shot 2023-10-05 at 12 06 38 PM" src="https://github.com/NCAR/DART/assets/142816397/8323a74a-1af8-4606-a744-d39ba522d4e9">

### Version of DART      
Which version of DART are you using? 
v10.8.4 

### Have you modified the DART code?   
No

### Build information
Please describe:  
 1. The machine you are running on (e.g. windows laptop, NCAR supercomputer Cheyenne).  *Derecho
 3. The compiler you are using (e.g. gnu, intel).  *nvhpc

**Comment by hkershaw-brown** [comment]
https://github.com/NCAR/DART/issues/219

**Comment by hkershaw-brown** [comment]
more specifically, this compiler flag 

https://github.com/NCAR/DART/issues/219#issuecomment-849012050

**Comment by ann-norcio** [comment]
Addressed this issue in #557
