### ISSUE TITLE
Feature request: obs_seq file splitting program

### ISSUE THREAD

**Issue by nancycollins** [NCAR/DART#556]
### Use case  
People frequently need obs_seq files split into multiple files that each cover a shorter time period

### Is your feature request related to a problem?  
we currently point people at a variety of shell scripts.  all of them are pretty incomprehensible because they have to do math with dates and convert between gregorian time (day/seconds since 1601) and Y/M/D/H/m/S time formats.  also, they use 'sed' to edit an input.nml to set the output filenames and start/stop times for each run of the obs_sequence_tool.  

### Describe your preferred solution  
A splitting program could hide all the date manipulations and be simpler to run.  I wrote up [this proposal document](https://docs.google.com/document/d/17GvpsdVyWQe4AEgIcjSPnYjVMYCM7pwagDGiQe7RJQ4/edit) for how a program like this could work.  The 'advance_time' program is a heavy inspiration for how to specify time intervals and output filenames.

### Describe any alternatives you have considered  
we can exist as we always have with shell scripts, but they're hard for users (they're often hard for me and i wrote a billion of them).

**Comment by hkershaw-brown** [comment]
Possible dupilcate/overlap https://github.com/NCAR/DART/issues/226

**Comment by hkershaw-brown** [comment]
merged this issue into #226
