### ISSUE TITLE
Feature request: Bringing DART documentation in accordance with "Official Policy on Brand Standards of the U.S. National Science Foundation"

### ISSUE THREAD

**Issue by johnsonbk** [NCAR/DART#584]
### Use case  
For DART users who are reading the documentation.

### Is your feature request related to a problem?  
NSF has updated their brand policy for federally funded research and development centers that are predominantly funded by NSF. NSF NCAR falls under this policy. The NSF NCAR logo must be paired with the NSF logo in all instances, with the NSF logo to the left and slightly larger than the NSF NCAR logo. Additionally, written descriptions of "NCAR" must be changed to "NSF NCAR."

### Describe your preferred solution  
Edit the documentation to change instances of "NCAR" to "NSF NCAR" and to modify the logo in the navigation menu to include the NSF logo.

### Describe any alternatives you have considered  
Waiting until there is an approved lockdown logo from NSF.

**Comment by hkershaw-brown** [comment]
fixed in #585
