### ISSUE TITLE
Remove shell_exit.sh in $DARTROOT/models/POP/shell_scripts?

### ISSUE THREAD

**Issue by johnsonb-ucar** [NCAR/DART#6]
I'm updating CESM_DART_config for POP and CESM2.

The script references shell_exit.sh which serves to provide the script an exit code if a serial section of the batch script exits on LSF.

There seems to be a maintained version shell_exit.sh script here:
`$DARTROOT/assimilation_code/scripts/shell_exit.sh`

For some reason, there's a not-exactly-duplicate version of the script in:
`$DARTROOT/models/POP/shell_scripts/shell_exit.sh`

As I'm updating the shell scripts in `$DARTROOT/models/POP/shell_scripts/cesm2_1` should I remove shell_exit.sh from the directory and references to it in CESM_DART_config?

**Comment by nancycollins** [comment]
i would remove the POP one.  i don't know how many LSF users we have, and whether LSF has fixed the exit code problems.  but we certainly don't need 2 only slightly different versions of this script.  i'd use the one in the assimilate_code dir.

**Comment by johnsonb-ucar** [comment]
Wilco.
