### ISSUE TITLE
Feature request: make it easier to compile parse_args_mod.f90 without special compiler flags

### ISSUE THREAD

**Issue by nancycollins** [NCAR/DART#607]
### Use case  
make it easier to compile the dart code by avoiding the need for special compiler flags

### Is your feature request related to a problem?  
the parse_args_mod.f90 file should have the existing code changed from using double backslash to:

```
! in re-reading this thread i am reminded that ACHAR is a way to set a character variable 
! without having an explicit backslash in the code and having to fool with compiler flags. 
! i think the fix for this and issue #555 should be:

character(len=1), parameter :: BACKSLASH = ACHAR(92)

...

if (thisc == BACKSLASH) then

```
### Describe your preferred solution  
don't depend on compiler flags to parse ```\\``` (double backslash)

### Describe any alternatives you have considered  
this is related to a long discussion in issue #219 which is closed now, and #555.    
marlee is trying to clean up the code and bring it up to current standards.  
this seems like a fix that fits into that goal.

**Comment by nancycollins** [comment]
i made this change on the fix_parse branch.

**Comment by hkershaw-brown** [comment]
related  #231

**Comment by mjs2369** [comment]
Files that use this flag: mkmf.template.nvhpv, mkmf.template.pgi.linux, mkmf.template.pgi.osx

**Comment by nancycollins** [comment]
if this does go into the repo as part of the 'fortran cleanup' effort, i've made a 'fix_parse' branch on my fork of the repo, and it only has the parse file changes without the unintended AIRS converter changes.
