### ISSUE TITLE
bug: arguments in the call to count_state_ens_copies 

### ISSUE THREAD

**Issue by jlaucar** [NCAR/DART#613]
The order of arguments in the call to count_state_ens_copies in filter_mod.f90 is inconsistent with the argument list in the function. The call has prior_inflate and posterior_inflate in this order as the second and third arguments; this is reversed in the function. 

This appears in all DART version since at least 2017.  

The impacts of this error are unclear. It is possible that some diagnostics output about inflation is mislabeled. It is possible that in some cases the diagnostic output is skipped.

**Comment by hkershaw-brown** [comment]
lines of code:
https://github.com/NCAR/DART/blob/99ebec56a6efdd243ed026da24b29a1a45bb8cdd/assimilation_code/modules/assimilation/filter_mod.f90#L462

https://github.com/NCAR/DART/blob/99ebec56a6efdd243ed026da24b29a1a45bb8cdd/assimilation_code/modules/assimilation/filter_mod.f90#L2242

mixture of module globals `do_prior_inflate` & querying the derived type `mean_from_restart(prior_inflate)`. Also passing in module globals as arguments:
https://github.com/NCAR/DART/blob/99ebec56a6efdd243ed026da24b29a1a45bb8cdd/assimilation_code/modules/assimilation/filter_mod.f90#L2282-L2286
