### ISSUE TITLE
CLM-DART SourceMod bug

### ISSUE THREAD

**Issue by braczka** [NCAR/DART#622]
### Describe the bug

Running CLM5_setup_assimilation leads to SourceMod path error.  Code cannot find SourceMod path which was made explicit in recent Derecho PR #611 

3. What was the expected outcome?
4. What actually happened?  

### Error Message  
Please provide any error messages.

### Which model(s) are you working with?
CLM5

### Version of DART      
Which version of DART are you using? 
v11.0.0

### Have you modified the DART code?   
Yes

### Build information
Please describe:  
 1. The machine you are running on (e.g. windows laptop, NCAR supercomputer Cheyenne).   
 Dercho
 3. The compiler you are using (e.g. gnu, intel).  
intel

**Comment by hkershaw-brown** [comment]
fixed in #623
