### ISSUE TITLE
Manhattan branch ... merging new content

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#63]
On August 14th, 2020 - I mistakenly merged a pull request against Manhattan instead of master. (This was PR#44) 
Those changes were intended for master, so I immediately reverted the merge (PR#45) and hoped for the best.
[Aside: I used a GitHub facility to revert the merge] 
All seemed well - until I wanted to update Manhattan for a new (minor) release. 

git now thinks the merge-base between Manhattan and master is b4ce252e00ebe14b157499706d66af0bbd2d5a9d
which was the last commit before the bad merge. This seems like the right commit - however, the commits to 
revert the bad merge (change/add a bunch of files, remove/revert those same files) are still intefering with attempts to 
merge the current master onto Manhattan. All attempts to update Manhattan seem to ignore the files from the original
bad merge - so those files (lots of them) remain unchanged or simply do not exist.

```
6b6c084c70c63ec05ba06a280ecb16e83b1e950d    bad commit (add new files, modify others)
72d905da819325bcb8c442f0bdcb6474cf2d32e8    commit to fix (i.e. delete, revert a bunch of files)
2a66909778450bcc2f585d20ee84eac944233de7    what I think should be the new merge-base
```

Until we figure out a way to fix the situation, I see no good path forward for clean upgrades from Manhattan to future releases.
My apologies ... this has been quite an illuminating mistake. 

If there is a git expert who can help me out of this predicament, I will be very grateful.

**Comment by hkershaw-brown** [comment]
closing this since new releases (since 9.10.0)  are tagged from the main branch.
& main is now the default branch.
