### ISSUE TITLE
Where is the filter_input.cdl of bgrid_solo?

### ISSUE THREAD

**Issue by lantel-wm** [NCAR/DART#647]
I'm new to DART, and I'm trying to run bgird_solo model. But I can't find the filter_input.cdl file, only a file named filter_input.cdl.REMOVED.git-id exists in the model's work folder. I'm wondering how I can get or generate filter_input.cdl file, I'll appreciate it if someone could help me. :)

### Describe the bug
Can't find filter_input.cdl.

### Error Message  
None.

### Which model(s) are you working with?
bgrid_solo.

### Version of DART      
v11.0.3

### Have you modified the DART code?   
No

**Comment by hkershaw-brown** [comment]
Hi lantel-wm, thanks for bringing this to our attention. filter_input.cdl.REMOVED.git-id isn't helpful for getting started.  We'll take a look at this.

Science wise, dart@ucar.edu is the place to ask about the experiment setup. It would be good to try the DART tutorial also.  But if you just want to try out filter with some brgid_solo files you can do the following to get a bgrid_solo netcdf file and perturb it to get an ensemble:

There is a perfect_input.cdl  in models/bgrid_solo/work 

./quickbuild.sh         (or quickbuild.sh nompi if you are not building with mpi)
This will create perfect_input.nc

./perfect_model_obs

cp perfect_output.nc filter_input.nc

in input.nml, set 
&filter_nml
perturb_from_single_instance = .true.,

Then you can run filter
./filter

Cheers,
Helen

**Comment by lantel-wm** [comment]
> Hi lantel-wm, thanks for bringing this to our attention. filter_input.cdl.REMOVED.git-id isn't helpful for getting started. We'll take a look at this.
> 
> Science wise, [dart@ucar.edu](mailto:dart@ucar.edu) is the place to ask about the experiment setup. It would be good to try the DART tutorial also. But if you just want to try out filter with some brgid_solo files you can do the following to get a bgrid_solo netcdf file and perturb it to get an ensemble:
> 
> There is a perfect_input.cdl in models/bgrid_solo/work
> 
> ./quickbuild.sh (or quickbuild.sh nompi if you are not building with mpi) This will create perfect_input.nc
> 
> ./perfect_model_obs
> 
> cp perfect_output.nc filter_input.nc
> 
> in input.nml, set &filter_nml perturb_from_single_instance = .true.,
> 
> Then you can run filter ./filter
> 
> Cheers, Helen

Thanks a lot, it really helps me. Sorry for asking about the experiment setup in the wrong place. I'm trying the DART tutorial as well, thank you for your kind reply!
