### ISSUE TITLE
QUESTION: multiple observation assimilation, the states are updated by unrelated observation

### ISSUE THREAD

**Issue by hgrhgy** [NCAR/DART#648]
### Describe the bug, MAYBE not a bug
when I tried to assimlate multiple observation (e.g. XCO2 XCO and XCH4 observation) ,  I suppose the CO2 observation is only affected the states related to the CO2.  Since the states of XCO2 XCO and XCH4 are perturbed and the variance of these states is not zero,  the CO2 observation will updated all the perturbed states.  It seems to be a one(obs)-to-many(states) mapping.

Is there any way to specify which states are related to a certain observation?

### Version of DART      
DART version 11.0.1

### Have you modified the DART code?   
No code modifed under dir  `assimilation_code`
porting new model of geoschem

### Build information
Please describe:  
 1. running on my local cluster
 2.  intel compiler

**Comment by hkershaw-brown** [comment]
Hi Hgrhgy, 

Please email us at dart@ucar.edu for support questions.

Cheer,
Helen
