### ISSUE TITLE
Add WRF sigma hybrid coordinate capability to DART

### ISSUE THREAD

**Issue by braczka** [NCAR/DART#649]
### Describe the bug

Bug reported by Arthur Mizzi: "The bug is that DART is using the Terrain Following Vertical Coordinate (TFVC) system for WRF, and now WRF can use either a TFVC or a Hybrid Vertical Coordinate (HVC) system 1."

This change to WRF code occurred prior to WRF4 version.  Recommended changes for DART code (WRF model_mod.f90) were included in a [wrf_hybrid branch](https://github.com/nancycollins/DART/blob/wrf_hybrid/models/wrf/model_mod.f90),  but currently not included in main.  

 Another offline recommended fix provided from Chia-Hua Hsu WRF-Chem version of code also provided to DART team.

### Error Message  
Error message not provided

### Which model(s) are you working with?
Sigma hybrid coordinate implemented prior to WRF4+ versions.  DART change should be compatible with WRF3 and WRF4.

### Version of DART      
DARTv11.0.3
 
### Have you modified the DART code?   
Will implement portion of code within (https://github.com/nancycollins/DART/blob/wrf_hybrid/models/wrf/model_mod.f90) that targets sigma hybrid coordinate and verify it works.

**Comment by hkershaw-brown** [comment]
Is there detail on 
> Another offline recommended fix provided from Chia-Hua Hsu WRF-Chem version of code also provided to DART team.
what the bug/fix is?

**Comment by braczka** [comment]
> Is there detail on
> 
> > Another offline recommended fix provided from Chia-Hua Hsu WRF-Chem version of code also provided to DART team.
> > what the bug/fix is?

It's basically the same fix  as included in the wrf_hybrid_branch, however the wrf_hybrid_branch fix works automatically -- it identifies if their are hybrid coordinates directly from the global attribute in the wrf file and applies the correct interpolation scheme, whereas the suggested offline fix, the user has to manually edit the source code to use the correct interpolation scheme, recompile etc.

**Comment by hkershaw-brown** [comment]
gotcha, different fix for the same bug.

**Comment by hkershaw-brown** [comment]
fixed in #650
