### ISSUE TITLE
Diagnostic failure (diagnostics_obs.csh) within WRF-DART Tutorial

### ISSUE THREAD

**Issue by braczka** [NCAR/DART#660]
### Describe the bug

Perform WRF-DART Tutorial per [documentation ](https://docs.dart.ucar.edu/en/latest/models/wrf/tutorial/README.html).  The tutorial will complete successfully.  No fatal errors, and almost all diagnostics are produced correctly with this exception.

What was the expected outcome?

Expectation is ``mean_increment.nc`` is generated successfully.

What actually happened?  

``Mean_increment.nc`` file is empty because of failure during execution of ``mean_increment.ncl`` as part of ``diagnostics_obs.csh`` during ``driver.csh`` step.

### Error Message  

The following appears within the obs_diag.log file:

```
Copyright (C) 1995-2019 - All Rights Reserved
 University Corporation for Atmospheric Research
 NCAR Command Language Version 6.6.2
 The use of this software is governed by a License Agreement.
 See http://www.ncl.ucar.edu/ for more details.
(0)        Extracting 2d variable T2_d01
fatal:No valid instance of variable T2_d01 found in file list
^Mfatal:["Execute.c":8637]:Execute: Error occurred at or near line 40 in file /glade/derecho/scratch/bmraczka/WRFv3.9.1_DART_Tutorial/output/2017042706/mean_increment.ncl
```

### Which model(s) are you working with?
WRFv3 or WRFv4

### Version of DART      

11.3.1

### Have you modified the DART code?   
No

### Build information
Derecho using gfortran

**Comment by hkershaw-brown** [comment]
fixed by #708
