### ISSUE TITLE
Feature request: ...add a new DART quality flag for output in obs_seq.final

### ISSUE THREAD

**Issue by prabshr** [NCAR/DART#675]
### Use case  
Need to add a new DART quality flag for output in obs_seq.final

### Is your feature request related to a problem?  
If the geolocation of  observation  is outside the cutoff radius specified in "input.nml" for the grids in model domain, DART prints out Quality Flag of "0" although the increments are zero and there is no difference between prior and posterior ensemble. This was observed for a point scale model run.

### Describe your preferred solution  
Maybe a new Quality Flag to tell users that the observation is outside the influence area for the model domain?

### Describe any alternatives you have considered  
The user will need to understand what is happening.

**Comment by hkershaw-brown** [comment]
Hi @prabshr, 

Just so we're on the same page about what you're requesting. Here's a sketch of a model domain which is a square with 9 grid points.

Do you mean the case where the cutoff (circle) is smaller than the grid spacing:
<img src="https://github.com/NCAR/DART/assets/20047007/dc62e07b-5dcc-4836-839d-de5493d8c97d" width="50%">

Or the observation being outside the grid? If the observation is outside the model grid, then the forward operator should fail, which would give a qc=4.  If you're in this situation and getting qc=0 then this might be a bug in the model_mod code.
<img src="https://github.com/NCAR/DART/assets/20047007/6347fdbd-9bbd-4c77-9069-5d4bbfa23059" width="70%">

**Comment by hkershaw-brown** [comment]
closing for now, will reopen if we get more info.
