### ISSUE TITLE
DART-LPF algorithm has incorrect pf_enkf_hybrid default option

### ISSUE THREAD

**Issue by braczka** [NCAR/DART#680]
### Describe the bug

Bug reported by WRF-DART user during implementation of Poterjoy particle filter (LPF) algorithm.  [See assim_tools_mod_pf.f90](https://github.com/braczka/DART/blob/main/assimilation_code/modules/assimilation/assim_tools_mod.pf.f90) 
 
_I just noticed that pf_enkf_hybrid is set to 'true' by default in assim_tools_mod. Because you did not specify this option in your namelist, you are actually running a combination of an LPF-EnKF update, as described in [this paper](https://journals.ametsoc.org/view/journals/mwre/151/1/MWR-D-22-0108.1.xml). I admit that this is an unfortunate default option (that should be changed in the DART repository) since it makes no sense for users to have to specify pf_enkf_hybrid in order to shut this feature off. In the meantime, set pf_enkf_hybrid = .false. under &assim_tools_nml in the namelist._

### Error Message  
No error message.

### Which model(s) are you working with?

WRF4+

### Version of DART      
DARTv10.10.1

**Comment by hkershaw-brown** [comment]
@braczka I'm going to go ahead and commit the  pf_enkf_hybrid=.false. to the WRF4_updates branch
