### ISSUE TITLE
guide/netcdf_inflation_files.rst doc error(?)

### ISSUE THREAD

**Issue by kdraeder** [NCAR/DART#692]
### Describe the bug
The section at the end about "multiple domains filter is expecting to write" seems to have not been updated
from "prior_inflation_restart"... to "output_priorinf"... etc.
I can't say for sure because I was unable to track down where those file names are created
and haven't taken the time to set up an assimilation to create the files.
I'll do that if this report seems misguided.

Also, just above that section, "filter is expecting to read:" should probably be "filter will write:"

### Screenshots   
![Screen Shot 2024-07-02 at 3 17 34 PM](https://github.com/NCAR/DART/assets/13259536/a3f54c9e-d50b-43e3-806e-db3ce604501e)

### Version of DART      
Which version of DART are you using? 
v11.4.1

### Have you modified the DART code?   
No

**Comment by hkershaw-brown** [comment]
@kdraeder if you're working on a fix for this, I'd say remove the file guide/netcdf_inflation_files.rst. 

The info is also here
https://docs.dart.ucar.edu/en/latest/assimilation_code/programs/filter/filter.html#files
and let's face it, probably 4 other places all giving slightly different info.  Maybe it is even in the inflation documentation. 
I'm not sure what the point of guide/netcdf_inflation_files.rst is.

**Comment by kdraeder** [comment]
I'm guessing that the purpose was to make in clear to existing users 
what the changes were, when we simplified the io file architecture.
I agree that it's more distracting than useful now, so it can be deleted.

guide/inflation.html#inflation could have a link to 
[latest/assimilation_code/programs/filter/filter.html#files](https://docs.dart.ucar.edu/en/latest/assimilation_code/programs/filter/filter.html#files)

My search "inflation stage filenames" doesn't yield any more terribly redundant information in the first page of results, 
so I don't see anything else to purge.
This seems too trivial to be useful for a student to learn from it, so I'll deal with it.
