### ISSUE TITLE
Comment not clear

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#70]
https://github.com/NCAR/DART/blob/18106dd410462cc96478b7a634d7c8ec08fea060/assimilation_code/modules/assimilation/filter_mod.f90#L192

`distributed_state = .true.` is ensemble complete, correct?

**Comment by nancycollins** [comment]
the terminology is always confusing to me.  inside the ensemble manager the terms are 'var complete' and 'copy complete'.  in the filter context, i guess it would still be 'copy complete' (meaning each task has all copies of a subset of the state vector) and 'ensemble complete' (each task has one or more entire state vectors).  i don't know if we use 'state complete' anywhere - but in any case i believe the more correct term here would be '... copy complete forward operators'.

**Comment by jlaucar** [comment]
Maybe I'm confused, but isn't this the namelist that controls whether the single copy of the ensemble mean state is distributed across tasks or not. It is not directly related to copy complete or ensemble complete notions for the ensemble state. I don't have time to prove myself wrong by looking at the code at the moment.

**Comment by nancycollins** [comment]
this namelist item controls the ensemble behavior for the state.  there is a different one for the mean.
