### ISSUE TITLE
readthedocs changes October 7 2024

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#703]
[Action required] Deprecation: Removal of Sphinx context injection at build time
https://about.readthedocs.com/blog/2024/07/addons-by-default/

**Deprecation timeline**
We understand this change will affect thousands of projects, so we have a timeline to communicate this deprecation to our users effectively.

July 29, 2024: disable Sphinx context injection and enable Read the Docs Addons for all new projects created.
**October 7, 2024**: disable Sphinx context injection and enable Read the Docs Addons for all projects.

**Comment by hkershaw-brown** [comment]
turned on addons and built readthedocs-test
https://docs.dart.ucar.edu/en/readthedocs-test/
seems fine.

**Comment by hkershaw-brown** [comment]
@ann-norcio @c-merchant @Benjamin-Gunn 
If you get a chance can you have a click around https://docs.dart.ucar.edu/en/readthedocs-test/
Readthedocs are updating how they build the documentation so it would be good to catch any weirdness before the Oct 7th switchover.

**Comment by hkershaw-brown** [comment]
having the add on seems to break the search on the 'lastest' docs. bummer.

**Comment by ann-norcio** [comment]
Noticed the same things Helen pointed out while clicking around https://docs.dart.ucar.edu/en/readthedocs-test/

- The versions are not listed in the correct order on the flyout menu
- Formatting of the table [here](https://docs.dart.ucar.edu/en/readthedocs-test/guide/required-model-mod-routines.html) is off, but it's also that way in the 'latest' version

**Comment by hkershaw-brown** [comment]
note on redirects.

old versions of the docs have README.html
The flyout links are index.html

If you redirect from as specific version /en/vX/ -> /en/vX/README.html
you can use the flyout menu from new to old, but not old new.

**Comment by hkershaw-brown** [comment]
general one way and specific back fixes the old doc flyout 404

![Screenshot 2024-07-24 at 3 02 54 PM](https://github.com/user-attachments/assets/822b44c4-be2b-4884-9dee-ebdc098460f9)

Note delete these if the redirects cause problems
