### ISSUE TITLE
DART download link

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#85]
2,254 mentions of

http://www.image.ucar.edu/DAReS/DART/DART_download

in the repo. 

1. I don't think this is the correct link - it goes to the subversion instructions
2. What is the correct link?

**Comment by timhoar** [comment]
Actually, it goes to the registration information which is being harvested by a DRUPAL form.
Once the person fills out the form, the instructions point them to the GitHub realm.


<img width="1058" alt="Screen Shot 2020-11-30 at 1 43 32 PM" src="https://user-images.githubusercontent.com/15146042/100662401-159d7280-3312-11eb-992c-da3072a0a058.png">

**Comment by hkershaw-brown** [comment]
when I click on the link I get taken to:

![Screen Shot 2020-11-30 at 1 45 52 PM](https://user-images.githubusercontent.com/20047007/100662806-a2483080-3312-11eb-940a-4443c49bcb62.png)

**Comment by timhoar** [comment]
I see your point.  I've been on that page so many times that I don't read the banner of the registration page.
I'll fix that (as soon as I can remember how to do this ... I have notes on editing Drupal pages ... very obtuse when you only change them once every few years)

**Comment by timhoar** [comment]
OK - give it a shot now and let me know what you think.
I removed the references to svn and replaced them with git and GitHub references.

**Comment by hkershaw-brown** [comment]
this is way better.

**Comment by hkershaw-brown** [comment]
I'll go ahead and close this issue.  Feel free to reopen if there is more to do, but it looks perfect to me.
