### ISSUE TITLE
Making the reanalysis branch public

### ISSUE THREAD

**Issue by kdraeder** [NCAR/DART#89]
Background:
I believe that I branched 'reanalysis' from the fork of Manhattan on github/kdraeder
more than a year ago. As I remember is, we intended that it would be a long-lived branch
on which I would make any changes needed to finish the Reanalysis efficiently,
which would not be completely merged back onto the main (some useful pieces would).
Most of the divergence involved the creation of lots of scripts for managing the Reanalysis,
most of which have (possibly outdated) versions in 
reanalysis:...models/cam-fv/shell_scripts/cesm2_1.
The most current versions are in 
github...DART/CASES/f.e21.FHIST_BGC.f09_025.CAM6assim.011.

There are also differences in some diagnostics/matlab scripts to accommodate my workflow
and the desired appearance of the pictures in group evaluation web sites.

The issue:
I'm writing a paper describing the Reanalysis for Scientific Data,
which requires (or at least strongly urges) that the code used to generate data
be made available for data replication tests and data verification.
So it seems that we need to make the reanalysis branch publicly available.

Another factor, which is not strictly a DART github issue, but may have some impact on how we proceed:
I also used a branch of CESM, which will never be merged back into the CESM main.
It's also archived on github:kdraeder.

There are several ways that I can see to make all the relevant code public, 
and probably more ways that I'm not aware of.  
Some features it should probably have:

1. Available reliably and indefinitely.
2. Cleaned up and documented enough to be useful,
3. which will probably involve testing
4. Not interfere with more "standard" cam-fv assimilation work.

**Comment by hkershaw-brown** [comment]
Just to keep track of what is what with the branches.  There is a branch on DART_development called reanalysis:

https://github.com/NCAR/DART_development/tree/reanalysis

Is this branch what was used for the reanalysis?  
Kevin do you have a fork of DART_development as well?

**Comment by kdraeder** [comment]
I'll try to be careful about my vocabulary, but confusion may ensue anyway.

I do have a fork of DART_development on kdraeder.
I developed the reanalysis branch on cheyenne (setup and run scripts)
and on my Mac (diagnostics scripts).
I'll need to look into whether I've committed those to kdraeder recently.
I should have, but need to check.
Whether or not I have, I believe that the kdraeder:DART_development:reanalysis
has _not_ been merged back to NCAR/DART_development with _all_ of my Mac changes,
and that was intentional.  It's one of the issues we'll need to resolve.
And probably not all of the cheyenne changes that should be committed have been
merged back to NCAR/DART_development.

**Comment by jlaucar** [comment]
Is it a problem to have a branch that is not 'folded back in' to the master? I thought one of the powers of git/github was the ability to memorialize things that don't necessarily move forward. Can't we just give the sha that corresponds to Kevin's branch as the info needed to document his code for the publication?

**Comment by hkershaw-brown** [comment]
correct -  it is no problem to have a branch that is not folded back into the master. 

However, DART_development is private, so any forks of DART_development (e.g.  kdraeder:DART_development) are private.  On github, you can not make fork of a private repository public.  Most likely, we don't want the whole of DART_development public anyway.  That is, I don't think we want to simply duplicate kdraeder:DART_development (~80 branches) in a public repo.

I think the most important step is for kdraeder:DART_development:reanalysis to be up to date with what was used for the reanalysis.   We can then push that branch to DART (the public repo) or other public repo of your choice.  (e.g. amazing-reanalysis.git)

Kevin this seems like a good topic for the next software meeting.  Do you want to go over this then?

**Comment by kdraeder** [comment]
That would be helpful.
I'll try to get a more detailed picture by then and identify any hurdles.

**Comment by kdraeder** [comment]
I believe that I've pushed everything that I need to from 

- glade: ~raeder/DART/reanalysis_git(/models/cam-fv/shell_scripts/cesm2_1) updated from work/raeder/Exp/f.e21.FHIST_BGC.f09_025.CAM6assim.011
- my Mac: ~raeder/DAI/reanalysis_git
to kdraeder:DART_development:reanalysis.

Is there anything else to do before trying to copy this branch to NCAR/DART?

**Comment by hkershaw-brown** [comment]
closing this since the reanalysis branch is now public at 
 https://github.com/NCAR/DART/tree/reanalysis

Also a tagged release at 
https://github.com/NCAR/DART/releases/tag/DS345.0
