### ISSUE TITLE
unit tests for RTTOV obs_def

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#91]
- [x] set_mw_metadata, set_visir_metadata `call grow_metadata` seems to be after the rttovkey+1. 
Not causing problems since the metadata is always bigger. Starting at`MAXrttovkey=1` and adding 10 visir obs, 10 mw obs: 
`size of obstype_metadata, visir_obs_metadata, mw_obs_metadata          48          16          32`
- [x] check `key_within_range` works
  only checks key `size(obstype_metadata)`  rather than `rttovkey` (useful length of metadata array). This is not sufficient for `get_expected_radiance`

- [x] check `grow_metadata` for mw an ir
       mw grows with the rttov key so it is overgrowing
````
 mwnum           0
  set_mw_metadata  Warning: key (          11 ) exceeds mw_obs_metadata length (           1 )
  set_mw_metadata ...  Increasing mw_obs_metadata to length            2
 rttovkey          11

````
- [x] check `obstype_subkey` works for mw and ir
  Put subkey into the obstype_metadata array

Other things to look at:

- [ ]  module initialized?  - not called for a lot of these subroutines.  test what happens. 

- [ ] `cloud_profile_setup`, `aerosol_profile_setup`, etc.  should there be a corresponding `cloud_profile_teardown`?  What happens when you call the forward operator again?

- [x] why do I have to have subroutines for mw and visir (and a set of keys for each)?  Can't the metadata for the obs just tell me whether the obs is visir or mw?
For now, keeping separate metadata arrays of `visir_metadata_type` and `mw_metadata_type`

- [ ] how does the 
"One would assume the number of levels would not change between calls, but check" in `do_forward` tie in with `arrays_prealloced` for building the columns in `get_expected_radiance`.  Can the number of levels change or not?

- [ ]  can the list of rttov options be wrapped up in a type?  big list of arguments passed around to several subroutines at the moment. 

- [ ]  how interconnected is this with the obs coverters? does the read/write rttov metadata have to be in the forward operator module?

**Comment by hkershaw-brown** [comment]
there is a local `visirnum` in `get_visir_metadata` and a module`visirnum`

**Comment by hkershaw-brown** [comment]
side question: why does only `./models/coamps_nest/navdas_innov_mod.f90` call `init_obs_def`?

**Comment by nancycollins** [comment]
hum, learn something new all the time.  it looks like that routine is an 'all-in-one' initializer for the obs_def derived type.  

99.99% of the rest of the system sets the individual fields using separate subroutines.  the coamps and coamps_nest code was written by tim whitcomb at the naval research lab (NRL) in monterey.  personal preference, i guess.

**Comment by hkershaw-brown** [comment]
Q. Where does rttov_sensor_db_file come from?

**Comment by timhoar** [comment]
observations/forward_operators/rttov_sensor_db.csv

**Comment by timhoar** [comment]
If the meaning of the question is more basic:   `git log --follow observations/forward_operators/rttov_sensor_db.csv` indicates that the `rttov_test.f90` program created the prototype from profiles that were distributed with RTTOV. I believe that Jeff S. then augmented it with profiles he thought would be of general use. The filenames referenced in the .csv file match the filenames in the RTTOV distrubution.  for RTTOV V12.3 thats the following directory:
```
rttov/12.3/rtcoef_rttov12/rttov7pred54L
```

Am I getting closer to answering the question?

**Comment by hkershaw-brown** [comment]
Yes thanks Tim,  I am digging these instant answers to questions!

So it is a DART created file.  That is the answer to my question.
