### ISSUE TITLE
Update POP initial ensemble scripts for cesm2_1

### ISSUE THREAD

**Issue by amrhein** [NCAR/DART#93]
The setup script

${DARTROOT}/models/POP/shell_scripts/cesm2_1/HPSS_get_ensemble

to stage a POP ensemble targeted Who Kim's JRA-forced POP runs on HPSS that have since been moved.

I plan to write a Python script that copies these from campaign storage, unzipping as necessary, and renames files to give 80 initial ensemble members staged in directory 

'/glade/scratch/'+USER+'/'+save_dir+'/'+'POP_ensemble_dir'

**Comment by hkershaw-brown** [comment]
Pull request https://github.com/NCAR/DART/pull/97 closes this issue.
