### ISSUE TITLE
AIRS AMSUA observation converter ... Zeeman coefficients and channels

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#99]
The `observations/obs_converter/AIRS/convert_amsu_L1.f90` ultimately requires two pieces of microwave metadata: `mag_field` and `cosbk`. The `amsua_netCDF_support_mod.f90` has a section that is supposed to fill in the microwave metadata for the `mag_field` and `cosbk` variables ... It is only executed if the `obs_def_rttov_nml:use_zeeman = .true.`. I have no idea which channels to support for this option, nor do I know the proper values to supply. 

I am really confused by the contraditions in the 
the RTTOV v12 User Guide Section 8.12 _**Zeeman effect for SSMIS and AMSU-A**_
and the information about the AMSU-A mission from Remote Sensing Systems.

In one case, only Channel 14 is affected, in the other, Channels 4-14 are affected.

http://www.remss.com/missions/amsu/ states that:

> Molecular Oxygen has a complex of relatively strong absorption lines near 60 GHz. ...
> The AMSU instruments are composed of 2 sub units, AMSU-A and AMSU-B.  AMSU-B is a humidity sounder
> (not discussed further), and AMSU-A is a 15-channel temperature sounder similar to MSU.
> Of the 15 channels, 11 (Channels 4 through 14) are located in the 60 GHz absorption complex and thus are
> most closely related to atmospheric temepratures at various heights above the surface.  

Which is true ... Channels 4-14 are 52.8, 53.596, 54.4, 54.94, 55.5, 57.29034, 57.29034, 57.29034, 57.29034, 57.29034, 57.29034 GHz, according to the `center_freq` variable in the data files from the NASA Earthdata Data Access Services website.

The RTTOV v12 user guide states that:

> For microwave sensors that have high peaking weighting functions in the mesosphere such as SSMIS,
> channels close to lines of molecular oxygen may be significantly affected by the redistribution of line intensity
> through Zeeman splitting as described in the RTTOV v10 Science and Validation Report. The absorption for the
> affected channels will depend on the strength and orientation of the magnetic field. You must specify two input
> variables for the geomagnetic field in the rttov_profiles structure, these being the magnitude, Be, of the field
> and the cosine, cosbk, of the angle between the field vector and the viewing path considered. For SSMIS,
> values will be available with the satellite data stream, and will therefore already match the geographical location
> and orientation of the viewing path. For AMSU-A, this is not the case, but the values may be obtained from
> a pre-computed look-up table.
>
> [snip paragraph about SSMIS]
> 
> For AMSU-A, only channel 14 is affected. This channel, while dominated by oxygen absorption, sounds lower
> down in the atmosphere than the Zeeman channels of SSMIS, and it is also located further from the oxygen
> line centres. The impact is therefore much smaller (~0.5K). If you run with a non-Zeeman coefficient file, all
> channels will use the usual set of mixed gas predictors and the Zeeman effect will not be represented in
> channel 14. If a Zeeman coefficient file is used, then a small set of additional predictors will be included.
> These will contribute for channel 14 but will be nullified for the other channels by zero coefficients.

Any help from the community would be appreciated.

**Comment by lgstarn** [comment]
The oxygen absorption line changes in the presence of a magnetic field, a phenomenon called the Zeeman effect. This really only matters for channels that peak in the mesosphere as stated. All of those AMSU/A channels are "close" to the oxygen absorption line, but precisely how close determines where they peak. A channel very, very close to the line will see saturation as soon as few oxygen molecules are encountered, i.e. very high in the atmosphere; a channel farther away needs to see a lot more oxygen molecules before saturation, so will peak lower.

I recommend to leave in support for the Zeeman effectnin general but comment it out for AMSU/A and wait for a user who cares about the approximately 0.5 K impact on channel 14. I believe NWP users are unlikely to use channel 14 for data assimilation.

-JS

**Comment by lgstarn** [comment]
https://www.researchgate.net/profile/Viju-John/publication/33689746/figure/fig9/AS:669384376864769@1536605080113/Atmospheric-zenith-opacity-due-to-oxygen-and-water-vapor-for-the-microwave-frequency.ppm

Here's a graphic for a visualization. Note the logarithmic scale

**Comment by lgstarn** [comment]
And here is what that corresponds to in terms of weighting function: https://www.drroyspencer.com/wp-content/uploads/AMSU-weighting-functions.gif

**Comment by timhoar** [comment]
I don't understand how the weighting function of channel 14 is any different than channels 9-14, which all have an identical center frequency: 57.29034 GHz. 

I will certainly comment out support for the Zeeman effect in general, and issue a statement to reference this issue.

**Comment by lgstarn** [comment]
While the centers are the same, they differ by the number of bands that are +/- averaged together.

https://www.star.nesdis.noaa.gov/mirs/amsua.php
